///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.LinkSpecific.Weapons.Association
{
    /// <summary>
    /// The ValidateAssociation recording.
    /// </summary>
    [TestModule("ccd75c73-d988-4f1a-81f8-a5bcd0d9d91e", ModuleType.Recording, 1)]
    public partial class ValidateAssociation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TacViewLib.TacViewLibWeapons repository.
        /// </summary>
        public static TacViewLib.TacViewLibWeapons repo = TacViewLib.TacViewLibWeapons.Instance;

        static ValidateAssociation instance = new ValidateAssociation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateAssociation()
        {
            tracknumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateAssociation Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable tracknumber.
        /// </summary>
        [TestVariable("c4bc59de-a873-4edf-af39-ef70e3ff8131")]
        public string tracknumber
        {
            get { return repo.tracknumber; }
            set { repo.tracknumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 250;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Validate_AssociationLine();
            Delay.Milliseconds(0);
            
            SetTrack1NumberInRepo();
            Delay.Milliseconds(0);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            ViewTrack1Properties();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.TabPageAssociations' at Center.", repo.FormMainCreate.TabPageAssociationsInfo, new RecordItemIndex(4));
            repo.FormMainCreate.TabPageAssociations.Click();
            Delay.Milliseconds(0);
            
            Validate_ListItemTrack1_Number();
            Delay.Milliseconds(0);
            
            Validate_ListItemAssociated_Track1_Number();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormAssociations.ButtonCLOSE' at Center.", repo.FormAssociations.ButtonCLOSEInfo, new RecordItemIndex(7));
            repo.FormAssociations.ButtonCLOSE.Click();
            Delay.Milliseconds(0);
            
            SetTrack2NumberInRepo();
            Delay.Milliseconds(0);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            ViewTrack2Properties();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.TabPageAssociations' at Center.", repo.FormMainCreate.TabPageAssociationsInfo, new RecordItemIndex(11));
            repo.FormMainCreate.TabPageAssociations.Click();
            Delay.Milliseconds(0);
            
            Validate_ListItemTrack2_Number();
            Delay.Milliseconds(0);
            
            Validate_ListItemAssociated_Track2_Number();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormAssociations.ButtonCLOSE' at Center.", repo.FormAssociations.ButtonCLOSEInfo, new RecordItemIndex(14));
            repo.FormAssociations.ButtonCLOSE.Click();
            Delay.Milliseconds(0);
            
            SetDropTrack1NumberInRepo();
            Delay.Milliseconds(0);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            DropTrack();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2000ms.", new RecordItemIndex(18));
            Delay.Duration(2000, false);
            
            Validate_DropTrack1();
            Delay.Milliseconds(0);
            
            SetDropTrack2NumberInRepo();
            Delay.Milliseconds(0);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            DropTrack2();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2000ms.", new RecordItemIndex(23));
            Delay.Duration(2000, false);
            
            Validate_DropTrack2();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
}
