///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.UISpecific.Overlays
{
	/// <summary>
	/// The CreatePolygon recording.
	/// </summary>
	[TestModule("53120787-0515-4b3f-b298-1500a0e06c19", ModuleType.Recording, 1)]
	public partial class CreatePolygon : ITestModule
	{
		/// <summary>
		/// Holds an instance of the TacViewLib.TacViewLibRepositoryOverlays repository.
		/// </summary>
		public static TacViewLib.TacViewLibRepositoryOverlays repo = TacViewLib.TacViewLibRepositoryOverlays.Instance;

		static CreatePolygon instance = new CreatePolygon();

		/// <summary>
		/// Constructs a new instance.
		/// </summary>
		public CreatePolygon()
		{
		}

		/// <summary>
		/// Gets a static instance of this recording.
		/// </summary>
		public static CreatePolygon Instance
		{
			get { return instance; }
		}

#region Variables

#endregion

		/// <summary>
		/// Starts the replay of the static recording <see cref="Instance"/>.
		/// </summary>
		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.0")]
		public static void Start()
		{
			TestModuleRunner.Run(Instance);
		}

		/// <summary>
		/// Performs the playback of actions in this recording.
		/// </summary>
		/// <remarks>You should not call this method directly, instead pass the module
		/// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
		/// that will in turn invoke this method.</remarks>
		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.0")]
		void ITestModule.Run()
		{
			Mouse.DefaultMoveTime = 150;
			Keyboard.DefaultKeyPressTime = 25;
			Delay.SpeedFactor = 1.0;

			Init();

			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.Button_Center_on_Own_Site1' at Center.", repo.FormTacViewC2____map__Defaul.Button_Center_on_Own_Site1Info, new RecordItemIndex(0));
			repo.FormTacViewC2____map__Defaul.Button_Center_on_Own_Site1.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ButtonSet_Range_to_500_km' at Center.", repo.FormTacViewC2____map__Defaul.ButtonSet_Range_to_500_kmInfo, new RecordItemIndex(1));
			repo.FormTacViewC2____map__Defaul.ButtonSet_Range_to_500_km.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ButtonPopup' at Center.", repo.FormTacViewC2____map__Defaul.ButtonPopupInfo, new RecordItemIndex(2));
			repo.FormTacViewC2____map__Defaul.ButtonPopup.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ContainerRvView2' at 160;98.", repo.FormTacViewC2____map__Defaul.ContainerRvView2Info, new RecordItemIndex(3));
			repo.FormTacViewC2____map__Defaul.ContainerRvView2.Click("160;98", 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ContainerRvView2' at 382;105.", repo.FormTacViewC2____map__Defaul.ContainerRvView2Info, new RecordItemIndex(4));
			repo.FormTacViewC2____map__Defaul.ContainerRvView2.Click("382;105", 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ContainerRvView2' at 369;248.", repo.FormTacViewC2____map__Defaul.ContainerRvView2Info, new RecordItemIndex(5));
			repo.FormTacViewC2____map__Defaul.ContainerRvView2.Click("369;248", 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ContainerRvView2' at 58;120.", repo.FormTacViewC2____map__Defaul.ContainerRvView2Info, new RecordItemIndex(6));
			repo.FormTacViewC2____map__Defaul.ContainerRvView2.Click("58;120", 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'FormTacViewC2____map__Defaul.ContainerRvView2' at 109;93.", repo.FormTacViewC2____map__Defaul.ContainerRvView2Info, new RecordItemIndex(7));
			repo.FormTacViewC2____map__Defaul.ContainerRvView2.Click(MouseButtons.Right, "109;93", 125);
			Delay.Milliseconds(0);
			
			Delay.Duration(500, false);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMain__ACM_Polygon_ACM_Po.Elements.ListItemACM_Type_and_Usage' at .02;.025.", repo.FormMain__ACM_Polygon_ACM_Po.Elements.ListItemACM_Type_and_UsageInfo, new RecordItemIndex(9));
			repo.FormMain__ACM_Polygon_ACM_Po.Elements.ListItemACM_Type_and_Usage.Click(".02;.025", 300);
			Delay.Milliseconds(200);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMain__ACM_Polygon_ACM_Po.Elements.ListItemOverlay_Name' at Center.", repo.FormMain__ACM_Polygon_ACM_Po.Elements.ListItemOverlay_NameInfo, new RecordItemIndex(10));
			repo.FormMain__ACM_Polygon_ACM_Po.Elements.ListItemOverlay_Name.Click(125);
			Delay.Milliseconds(0);
			
			// overlay name
			Report.Log(ReportLevel.Info, "Keyboard", "overlay name\r\nKey sequence '{Tab}{LShiftKey down}P{LShiftKey up}olygon{LShiftKey down}T{LShiftKey up}est{Return}'.", new RecordItemIndex(11));
			Keyboard.Press("{Tab}{LShiftKey down}P{LShiftKey up}olygon{LShiftKey down}T{LShiftKey up}est{Return}", 100);
			Delay.Milliseconds(0);
			
			// lower altitude
			Report.Log(ReportLevel.Info, "Keyboard", "lower altitude\r\nKey sequence '100{Return}'.", new RecordItemIndex(12));
			Keyboard.Press("100{Return}", 100);
			Delay.Milliseconds(0);
			
			// lower altitude indicator
			Report.Log(ReportLevel.Info, "Keyboard", "lower altitude indicator\r\nKey sequence 'flight{Return}'.", new RecordItemIndex(13));
			Keyboard.Press("flight{Return}", 100);
			Delay.Milliseconds(0);
			
			// upper altitude
			Report.Log(ReportLevel.Info, "Keyboard", "upper altitude\r\nKey sequence '500{Return}'.", new RecordItemIndex(14));
			Keyboard.Press("500{Return}", 100);
			Delay.Milliseconds(0);
			
			// uppper altitude indicator
			Report.Log(ReportLevel.Info, "Keyboard", "uppper altitude indicator\r\nKey sequence 'hae{Return}'.", new RecordItemIndex(15));
			Keyboard.Press("hae{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}{Return}{Return}'.", new RecordItemIndex(16));
			Keyboard.Press("{Return}{Return}{Return}", 100);
			Delay.Milliseconds(0);
			
			// starttime
			Report.Log(ReportLevel.Info, "Keyboard", "starttime\r\nKey sequence '5'.", new RecordItemIndex(17));
			Keyboard.Press("5", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}{Return}{Return}{Return}'.", new RecordItemIndex(18));
			Keyboard.Press("{Return}{Return}{Return}{Return}", 100);
			Delay.Milliseconds(0);
			
			// endtime
			Report.Log(ReportLevel.Info, "Keyboard", "endtime\r\nKey sequence '6'.", new RecordItemIndex(19));
			Keyboard.Press("6", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}{Return}{Tab}{Tab}{Tab}{Tab}{Tab}{Down}{Tab}{Tab}'.", new RecordItemIndex(20));
			Keyboard.Press("{Return}{Return}{Tab}{Tab}{Tab}{Tab}{Tab}{Down}{Tab}{Tab}", 100);
			Delay.Milliseconds(0);
			
			// radiofreq1 and units
			Report.Log(ReportLevel.Info, "Keyboard", "radiofreq1 and units\r\nKey sequence '1{Tab}{Tab}{Down}{Tab}{Tab}'.", new RecordItemIndex(21));
			Keyboard.Press("1{Tab}{Tab}{Down}{Tab}{Tab}", 100);
			Delay.Milliseconds(0);
			
			// radiofreq2 and units
			Report.Log(ReportLevel.Info, "Keyboard", "radiofreq2 and units\r\nKey sequence '2{Tab}{Tab}{Down}{Down}{Tab}{Tab}'.", new RecordItemIndex(22));
			Keyboard.Press("2{Tab}{Tab}{Down}{Down}{Tab}{Tab}", 100);
			Delay.Milliseconds(0);
			
			// radiofreq3 and units
			Report.Log(ReportLevel.Info, "Keyboard", "radiofreq3 and units\r\nKey sequence '3{Tab}{Tab}{Down}{Down}{Down}{Tab}{Tab}'.", new RecordItemIndex(23));
			Keyboard.Press("3{Tab}{Tab}{Down}{Down}{Down}{Tab}{Tab}", 100);
			Delay.Milliseconds(0);
			
			// radiofreq4 and units
			Report.Log(ReportLevel.Info, "Keyboard", "radiofreq4 and units\r\nKey sequence '4{Tab}{Tab}{Down}{Down}{Down}{Down}{Tab}{Tab}'.", new RecordItemIndex(24));
			Keyboard.Press("4{Tab}{Tab}{Down}{Down}{Down}{Down}{Tab}{Tab}", 100);
			Delay.Milliseconds(0);
			
			// radiofreq5 and units
			Report.Log(ReportLevel.Info, "Keyboard", "radiofreq5 and units\r\nKey sequence '5{Tab}{Tab}{Down}{Down}{Down}{Down}{Down}{Tab}{Tab}'.", new RecordItemIndex(25));
			Keyboard.Press("5{Tab}{Tab}{Down}{Down}{Down}{Down}{Down}{Tab}{Tab}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}A{LShiftKey up}mplification{LShiftKey down}T{LShiftKey up}est{Return}'.", new RecordItemIndex(26));
			Keyboard.Press("{LShiftKey down}A{LShiftKey up}mplification{LShiftKey down}T{LShiftKey up}est{Return}", 100);
			Delay.Milliseconds(5430);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}I{LShiftKey up}ndicator{LShiftKey down}T{LShiftKey up}est{Return}'.", new RecordItemIndex(27));
			Keyboard.Press("{LShiftKey down}I{LShiftKey up}ndicator{LShiftKey down}T{LShiftKey up}est{Return}", 100);
			Delay.Milliseconds(1480);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}F{LShiftKey up}ree{LShiftKey down}T{LShiftKey up}ext{LShiftKey down}T{LShiftKey up}est{Return}'.", new RecordItemIndex(28));
			Keyboard.Press("{LShiftKey down}F{LShiftKey up}ree{LShiftKey down}T{LShiftKey up}ext{LShiftKey down}T{LShiftKey up}est{Return}", 100);
			Delay.Milliseconds(8380);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMain__ACM_Polygon_ACM_Po.Container.ButtonSave' at Center.", repo.FormMain__ACM_Polygon_ACM_Po.Container.ButtonSaveInfo, new RecordItemIndex(29));
			repo.FormMain__ACM_Polygon_ACM_Po.Container.ButtonSave.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMain__ACM_Polygon_ACM_Po.ButtonCLOSE' at Center.", repo.FormMain__ACM_Polygon_ACM_Po.ButtonCLOSEInfo, new RecordItemIndex(30));
			repo.FormMain__ACM_Polygon_ACM_Po.ButtonCLOSE.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleName='PolygonTest') on item 'FormTacViewC2____map__Defaul.PicturePolygonTest'.", repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo, new RecordItemIndex(31));
			Validate.Attribute(repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo, "AccessibleName", "PolygonTest");
			Delay.Milliseconds(120);
			
			Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleValue='POLYGON') on item 'FormTacViewC2____map__Defaul.PicturePolygonTest'.", repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo, new RecordItemIndex(32));
			Validate.Attribute(repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo, "AccessibleValue", "POLYGON");
			Delay.Milliseconds(120);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'FormTacViewC2____map__Defaul.PicturePolygonTest' at Center.", repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo, new RecordItemIndex(33));
			repo.FormTacViewC2____map__Defaul.PicturePolygonTest.Click(MouseButtons.Right, 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemDelete_Overlay' at Center.", repo.FormRealView.MenuItemDelete_OverlayInfo, new RecordItemIndex(34));
			repo.FormRealView.MenuItemDelete_Overlay.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Are you sure you want to delete 'PolygonTest'?') on item 'RealViewDialog.TextAre_you_sure_you_want_to'.", repo.RealViewDialog.TextAre_you_sure_you_want_toInfo, new RecordItemIndex(35));
			Validate.Attribute(repo.RealViewDialog.TextAre_you_sure_you_want_toInfo, "Text", "Are you sure you want to delete 'PolygonTest'?");
			Delay.Milliseconds(120);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RealViewDialog.ButtonYes' at Center.", repo.RealViewDialog.ButtonYesInfo, new RecordItemIndex(36));
			repo.RealViewDialog.ButtonYes.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'FormTacViewC2____map__Defaul.PicturePolygonTest'.", repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo, new RecordItemIndex(37));
			Validate.NotExists(repo.FormTacViewC2____map__Defaul.PicturePolygonTestInfo);
			Delay.Milliseconds(120);
			
		}

#region Image Feature Data
#endregion
	}
}
