///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace SystemManagerLib.DLR
{
	/// <summary>
	/// The DLR_MTC recording.
	/// </summary>
	public partial class DLR_MTC
	{
		static DLR_MTC()
		{
			Report.Info("DLR'ing MTC Link");
			//Your recording specific initialization code goes here.
		}

		public void enterPort()
		{
			Report.Info("Key sequence port number");
			Keyboard.Press(port);
		}

		public void enterIP()
		{
			Report.Info("Key sequence ipval.");
			string[] output = ip.Split('.');
			string w = output[0].ToString();
			string x = output[1].ToString();
			string y = output[2].ToString();
			string z = output[3].ToString();
			string a = w.PadLeft(3,'0');
			string b = x.PadLeft(3,'0');
			string c = y.PadLeft(3,'0');
			string d = z.PadLeft(3,'0');
			Keyboard.Press(a);
			Keyboard.Press(b);
			Keyboard.Press(c);
			Keyboard.Press(d);
		}

		public void ClientServer()
		{
			if(serverclient == "client"){
				Report.Info("Setting as Client");
				repo.FormConfigure_Link.ButtonOpen.Click("6;9");
				Report.Info("Mouse Left Click item 'FormSm.ListItemClient' at 24;9.");
				repo.FormSm.ListItemClient.Click("24;9");				
			}
			else
			{
				// Leave as default if server
				Report.Info("Setting as Server");
			}
		}

		private void Init()
		{
			// Your recording specific initialization code goes here.
		}


	}
}
