///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.Defects.D01709
{
	/// <summary>
	/// The D01709 recording.
	/// </summary>
	public partial class D01709
	{
		public TacViewLib.TacViewSustainment_DefectsRepository repo = TacViewLib.TacViewSustainment_DefectsRepository.Instance;

		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "2.3.8")]
		public void Start()
		{
			Mouse.DefaultMoveTime = 300;
			Keyboard.DefaultKeyPressTime = 100;
			Delay.SpeedFactor = 1.0;

		}

#region Image Feature Data
#endregion
	}
}
