///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SystemManagerLib.TabSpecific.ForwardingTab
{
    /// <summary>
    /// The TurnOnAllForwarding recording.
    /// </summary>
    [TestModule("d8ffddc3-a0b0-4ce3-a6e5-0a92cc37d024", ModuleType.Recording, 1)]
    public partial class TurnOnAllForwarding : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SystemManagerLib.V15SmokeTestRepository repository.
        /// </summary>
        public static SystemManagerLib.V15SmokeTestRepository repo = SystemManagerLib.V15SmokeTestRepository.Instance;

        static TurnOnAllForwarding instance = new TurnOnAllForwarding();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TurnOnAllForwarding()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TurnOnAllForwarding Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 250;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.TitleBarSystem_Manager___UNCLASS' at Center.", repo.FormSystem_Manager___UNCLASS.TitleBarSystem_Manager___UNCLASSInfo, new RecordItemIndex(0));
            repo.FormSystem_Manager___UNCLASS.TitleBarSystem_Manager___UNCLASS.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.TabPageForwarding' at Center.", repo.FormSystem_Manager___UNCLASS.TabPageForwardingInfo, new RecordItemIndex(1));
            repo.FormSystem_Manager___UNCLASS.TabPageForwarding.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ListItem__Data_Link_Forwarding' at Center.", repo.FormSystem_Manager___UNCLASS.ListItem__Data_Link_ForwardingInfo, new RecordItemIndex(2));
            repo.FormSystem_Manager___UNCLASS.ListItem__Data_Link_Forwarding.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.TextEnable_All' at Center.", repo.FormSystem_Manager___UNCLASS.TextEnable_AllInfo, new RecordItemIndex(3));
            repo.FormSystem_Manager___UNCLASS.TextEnable_All.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ButtonApply' at Center.", repo.FormSystem_Manager___UNCLASS.ButtonApplyInfo, new RecordItemIndex(4));
            repo.FormSystem_Manager___UNCLASS.ButtonApply.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ListItem__C2_Host_Forwarding' at Center.", repo.FormSystem_Manager___UNCLASS.ListItem__C2_Host_ForwardingInfo, new RecordItemIndex(5));
            repo.FormSystem_Manager___UNCLASS.ListItem__C2_Host_Forwarding.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.TextEnable_All' at Center.", repo.FormSystem_Manager___UNCLASS.TextEnable_AllInfo, new RecordItemIndex(6));
            repo.FormSystem_Manager___UNCLASS.TextEnable_All.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ButtonApply' at Center.", repo.FormSystem_Manager___UNCLASS.ButtonApplyInfo, new RecordItemIndex(7));
            repo.FormSystem_Manager___UNCLASS.ButtonApply.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
}
