///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.Defects.Drop_Track
{
    /// <summary>
    /// The DropTrack recording.
    /// </summary>
    [TestModule("58d75df0-210b-42c2-a08e-ab81e6b14b62", ModuleType.Recording, 1)]
    public partial class DropTrack : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TacViewLib.TacViewSustainment_DefectsRepository repository.
        /// </summary>
        public static TacViewLib.TacViewSustainment_DefectsRepository repo = TacViewLib.TacViewSustainment_DefectsRepository.Instance;

        static DropTrack instance = new DropTrack();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DropTrack()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DropTrack Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 250;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            DropTrackSequence();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
}
