///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConfigurationWizardLib
{
    /// <summary>
    /// The class representing the Link_16_RegressionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1"), RepositoryFolder("1d0fb510-0cff-44bd-b0d2-136752abd997")]
    public partial class Link_16_RegressionRepository : RepoGenBaseFolder
    {
        static Link_16_RegressionRepository instance = new Link_16_RegressionRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Link_16_RegressionRepository element repository.
        /// </summary>
        [RepositoryFolder("1d0fb510-0cff-44bd-b0d2-136752abd997")]
        public static Link_16_RegressionRepository Instance {
            get { return instance; }
        }

        Link_16_RegressionRepositoryFolders.DesktopExplorerAppFolder _desktopexplorer;
        Link_16_RegressionRepositoryFolders.FormConfiguration_WizardAppFolder _formconfiguration_wizard;
        Link_16_RegressionRepositoryFolders.FormSelect_Configuration_FilAppFolder _formselect_configuration_fil;
        Link_16_RegressionRepositoryFolders.FormAccept_ConfigurationAppFolder _formaccept_configuration;
        Link_16_RegressionRepositoryFolders.FormUnsaved_ChangesAppFolder _formunsaved_changes;
        RepoItemInfo _buttoncloseInfo;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Link_16_RegressionRepository() : base("Link_16_RegressionRepository", "", null, 30000, false)
        {
            _desktopexplorer = new Link_16_RegressionRepositoryFolders.DesktopExplorerAppFolder(this);
            _formconfiguration_wizard = new Link_16_RegressionRepositoryFolders.FormConfiguration_WizardAppFolder(this);
            _formselect_configuration_fil = new Link_16_RegressionRepositoryFolders.FormSelect_Configuration_FilAppFolder(this);
            _formaccept_configuration = new Link_16_RegressionRepositoryFolders.FormAccept_ConfigurationAppFolder(this);
            _formunsaved_changes = new Link_16_RegressionRepositoryFolders.FormUnsaved_ChangesAppFolder(this);
            _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "/form[@title='cfgwizard']/.//button[@accessiblename='Close']", 10000, null, "13cb1ee1-11d1-4a95-b50d-5cead398905a");
        }

#region Variables

#endregion

        // <summary>
        /// The ButtonClose item.
        /// </summary>
        [RepositoryItem("13cb1ee1-11d1-4a95-b50d-5cead398905a")]
        public virtual Ranorex.Button ButtonClose
        {
            get
            {
                 return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
            }
        }

        /// <summary>
        /// The ButtonClose item info.
        /// </summary
        [RepositoryItemInfo("13cb1ee1-11d1-4a95-b50d-5cead398905a")]
        public virtual RepoItemInfo ButtonCloseInfo
        {
            get
            {
                return _buttoncloseInfo;
            }
        }

        /// <summary>
        /// The DesktopExplorer folder.
        /// </summary>
        [RepositoryFolder("88554ef3-702c-477e-8808-3c7df3f7a76f")]
        public virtual Link_16_RegressionRepositoryFolders.DesktopExplorerAppFolder DesktopExplorer
        {
            get { return _desktopexplorer; }
        }

        /// <summary>
        /// The FormConfiguration_Wizard folder.
        /// </summary>
        [RepositoryFolder("a0f88622-0c83-4770-8de5-a431d3d0ab57")]
        public virtual Link_16_RegressionRepositoryFolders.FormConfiguration_WizardAppFolder FormConfiguration_Wizard
        {
            get { return _formconfiguration_wizard; }
        }

        /// <summary>
        /// The FormSelect_Configuration_Fil folder.
        /// </summary>
        [RepositoryFolder("1ccc7d83-b6fd-4ee0-87d4-50884a19487f")]
        public virtual Link_16_RegressionRepositoryFolders.FormSelect_Configuration_FilAppFolder FormSelect_Configuration_Fil
        {
            get { return _formselect_configuration_fil; }
        }

        /// <summary>
        /// The FormAccept_Configuration folder.
        /// </summary>
        [RepositoryFolder("10b00ab7-bca8-4291-8248-c9b975b8daad")]
        public virtual Link_16_RegressionRepositoryFolders.FormAccept_ConfigurationAppFolder FormAccept_Configuration
        {
            get { return _formaccept_configuration; }
        }

        /// <summary>
        /// The FormUnsaved_Changes folder.
        /// </summary>
        [RepositoryFolder("f3488371-27c6-4a63-9297-f59c52198c93")]
        public virtual Link_16_RegressionRepositoryFolders.FormUnsaved_ChangesAppFolder FormUnsaved_Changes
        {
            get { return _formunsaved_changes; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class Link_16_RegressionRepositoryFolders
    {
        /// <summary>
        /// The DesktopExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("88554ef3-702c-477e-8808-3c7df3f7a76f")]
        public partial class DesktopExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _listitemconfig_wizardInfo;

            /// <summary>
            /// Creates a new DesktopExplorer  folder.
            /// </summary>
            public DesktopExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DesktopExplorer", "/desktop[@processname='explorer']", parentFolder, 30000, true, "88554ef3-702c-477e-8808-3c7df3f7a76f")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "88554ef3-702c-477e-8808-3c7df3f7a76f");
                _listitemconfig_wizardInfo = new RepoItemInfo(this, "ListItemConfig_Wizard", "container/list/listitem[@text='Config Wizard']", 10000, null, "779b1982-9d93-450c-a641-c8f86f52d4de");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88554ef3-702c-477e-8808-3c7df3f7a76f")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88554ef3-702c-477e-8808-3c7df3f7a76f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ListItemConfig_Wizard item.
            /// </summary>
            [RepositoryItem("779b1982-9d93-450c-a641-c8f86f52d4de")]
            public virtual Ranorex.ListItem ListItemConfig_Wizard
            {
                get
                {
                    return _listitemconfig_wizardInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemConfig_Wizard item info.
            /// </summary>
            [RepositoryItemInfo("779b1982-9d93-450c-a641-c8f86f52d4de")]
            public virtual RepoItemInfo ListItemConfig_WizardInfo
            {
                get
                {
                    return _listitemconfig_wizardInfo;
                }
            }
        }

        /// <summary>
        /// The FormConfiguration_WizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("a0f88622-0c83-4770-8de5-a431d3d0ab57")]
        public partial class FormConfiguration_WizardAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _radiobuttonopen_a_saved_configuratiInfo;
            RepoItemInfo _buttonbrowseInfo;
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _buttonstart_hardware_checkInfo;
            RepoItemInfo _buttonfinishInfo;
            RepoItemInfo _buttonmaximizeInfo;
            RepoItemInfo _buttonaccept_configurationInfo;
            RepoItemInfo _radiobuttonipv4Info;
            RepoItemInfo _textethernetInfo;
            RepoItemInfo _menuitemexitInfo;
            RepoItemInfo _formconfiguration_wizardInfo;

            /// <summary>
            /// Creates a new FormConfiguration_Wizard  folder.
            /// </summary>
            public FormConfiguration_WizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormConfiguration_Wizard", "/form[@title='Configuration Wizard']", parentFolder, 30000, true, "a0f88622-0c83-4770-8de5-a431d3d0ab57")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "a0f88622-0c83-4770-8de5-a431d3d0ab57");
                _radiobuttonopen_a_saved_configuratiInfo = new RepoItemInfo(this, "RadioButtonOpen_a_Saved_Configurati", ".//radiobutton[@accessiblename~'^Open\\ a\\ Saved\\ Configuratio']", 30000, null, "bd6a27fd-dcba-4d9b-9136-a55c50e98257");
                _buttonbrowseInfo = new RepoItemInfo(this, "ButtonBrowse", ".//button[@accessiblename='Browse']", 10000, null, "6788b8a2-d1af-4b49-bda7-1e795e4a396b");
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", ".//button[@accessiblename='Next >>']", 10000, null, "f6fe2f60-acf8-495a-8289-2f9942a58b2d");
                _buttonstart_hardware_checkInfo = new RepoItemInfo(this, "ButtonStart_Hardware_Check", ".//button[@accessiblename='Start Hardware Check']", 10000, null, "3a737bf0-8e02-40ff-8c84-2becdc5cc24d");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", ".//button[@accessiblename='Finish']", 10000, null, "271ce64c-f811-44c0-b79c-341f6dba4f41");
                _buttonmaximizeInfo = new RepoItemInfo(this, "ButtonMaximize", "titlebar/button[@accessiblename='Maximize']", 10000, null, "3157f4d4-7816-416c-a2c2-f249e8520ca7");
                _buttonaccept_configurationInfo = new RepoItemInfo(this, "ButtonAccept_Configuration", ".//button[@accessiblename='Accept Configuration']", 10000, null, "f83498f6-4702-4b5e-b594-bc3c12198dd1");
                _radiobuttonipv4Info = new RepoItemInfo(this, "RadioButtonIPv4", ".//radiobutton[@accessiblename='IPv4']", 10000, null, "07878719-450d-403a-a8a3-45b9d4af5594");
                _textethernetInfo = new RepoItemInfo(this, "TextEthernet", ".//text[@accessiblename='Ethernet']", 30000, null, "dde9e22b-9eee-4e1f-a979-600be80ee355");
                _menuitemexitInfo = new RepoItemInfo(this, "MenuItemExit", ".//menuitem[@accessiblename='Exit']", 10000, null, "6d3633fc-9f68-4a30-86c3-9ca000de2a3d");
                _formconfiguration_wizardInfo = new RepoItemInfo(this, "FormConfiguration_Wizard", "", 20000, null, "d28820b1-7fdf-4079-856f-28b396ae6e5b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0f88622-0c83-4770-8de5-a431d3d0ab57")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0f88622-0c83-4770-8de5-a431d3d0ab57")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RadioButtonOpen_a_Saved_Configurati item.
            /// </summary>
            [RepositoryItem("bd6a27fd-dcba-4d9b-9136-a55c50e98257")]
            public virtual Ranorex.RadioButton RadioButtonOpen_a_Saved_Configurati
            {
                get
                {
                    return _radiobuttonopen_a_saved_configuratiInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonOpen_a_Saved_Configurati item info.
            /// </summary>
            [RepositoryItemInfo("bd6a27fd-dcba-4d9b-9136-a55c50e98257")]
            public virtual RepoItemInfo RadioButtonOpen_a_Saved_ConfiguratiInfo
            {
                get
                {
                    return _radiobuttonopen_a_saved_configuratiInfo;
                }
            }

            /// <summary>
            /// The ButtonBrowse item.
            /// </summary>
            [RepositoryItem("6788b8a2-d1af-4b49-bda7-1e795e4a396b")]
            public virtual Ranorex.Button ButtonBrowse
            {
                get
                {
                    return _buttonbrowseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBrowse item info.
            /// </summary>
            [RepositoryItemInfo("6788b8a2-d1af-4b49-bda7-1e795e4a396b")]
            public virtual RepoItemInfo ButtonBrowseInfo
            {
                get
                {
                    return _buttonbrowseInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("f6fe2f60-acf8-495a-8289-2f9942a58b2d")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("f6fe2f60-acf8-495a-8289-2f9942a58b2d")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The ButtonStart_Hardware_Check item.
            /// </summary>
            [RepositoryItem("3a737bf0-8e02-40ff-8c84-2becdc5cc24d")]
            public virtual Ranorex.Button ButtonStart_Hardware_Check
            {
                get
                {
                    return _buttonstart_hardware_checkInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonStart_Hardware_Check item info.
            /// </summary>
            [RepositoryItemInfo("3a737bf0-8e02-40ff-8c84-2becdc5cc24d")]
            public virtual RepoItemInfo ButtonStart_Hardware_CheckInfo
            {
                get
                {
                    return _buttonstart_hardware_checkInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("271ce64c-f811-44c0-b79c-341f6dba4f41")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("271ce64c-f811-44c0-b79c-341f6dba4f41")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }

            /// <summary>
            /// The ButtonMaximize item.
            /// </summary>
            [RepositoryItem("3157f4d4-7816-416c-a2c2-f249e8520ca7")]
            public virtual Ranorex.Button ButtonMaximize
            {
                get
                {
                    return _buttonmaximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonMaximize item info.
            /// </summary>
            [RepositoryItemInfo("3157f4d4-7816-416c-a2c2-f249e8520ca7")]
            public virtual RepoItemInfo ButtonMaximizeInfo
            {
                get
                {
                    return _buttonmaximizeInfo;
                }
            }

            /// <summary>
            /// The ButtonAccept_Configuration item.
            /// </summary>
            [RepositoryItem("f83498f6-4702-4b5e-b594-bc3c12198dd1")]
            public virtual Ranorex.Button ButtonAccept_Configuration
            {
                get
                {
                    return _buttonaccept_configurationInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAccept_Configuration item info.
            /// </summary>
            [RepositoryItemInfo("f83498f6-4702-4b5e-b594-bc3c12198dd1")]
            public virtual RepoItemInfo ButtonAccept_ConfigurationInfo
            {
                get
                {
                    return _buttonaccept_configurationInfo;
                }
            }

            /// <summary>
            /// The RadioButtonIPv4 item.
            /// </summary>
            [RepositoryItem("07878719-450d-403a-a8a3-45b9d4af5594")]
            public virtual Ranorex.RadioButton RadioButtonIPv4
            {
                get
                {
                    return _radiobuttonipv4Info.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonIPv4 item info.
            /// </summary>
            [RepositoryItemInfo("07878719-450d-403a-a8a3-45b9d4af5594")]
            public virtual RepoItemInfo RadioButtonIPv4Info
            {
                get
                {
                    return _radiobuttonipv4Info;
                }
            }

            /// <summary>
            /// The TextEthernet item.
            /// </summary>
            [RepositoryItem("dde9e22b-9eee-4e1f-a979-600be80ee355")]
            public virtual Ranorex.Text TextEthernet
            {
                get
                {
                    return _textethernetInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextEthernet item info.
            /// </summary>
            [RepositoryItemInfo("dde9e22b-9eee-4e1f-a979-600be80ee355")]
            public virtual RepoItemInfo TextEthernetInfo
            {
                get
                {
                    return _textethernetInfo;
                }
            }

            /// <summary>
            /// The MenuItemExit item.
            /// </summary>
            [RepositoryItem("6d3633fc-9f68-4a30-86c3-9ca000de2a3d")]
            public virtual Ranorex.MenuItem MenuItemExit
            {
                get
                {
                    return _menuitemexitInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemExit item info.
            /// </summary>
            [RepositoryItemInfo("6d3633fc-9f68-4a30-86c3-9ca000de2a3d")]
            public virtual RepoItemInfo MenuItemExitInfo
            {
                get
                {
                    return _menuitemexitInfo;
                }
            }

            /// <summary>
            /// The FormConfiguration_Wizard item.
            /// </summary>
            [RepositoryItem("d28820b1-7fdf-4079-856f-28b396ae6e5b")]
            public virtual Ranorex.Form FormConfiguration_Wizard
            {
                get
                {
                    return _formconfiguration_wizardInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The FormConfiguration_Wizard item info.
            /// </summary>
            [RepositoryItemInfo("d28820b1-7fdf-4079-856f-28b396ae6e5b")]
            public virtual RepoItemInfo FormConfiguration_WizardInfo
            {
                get
                {
                    return _formconfiguration_wizardInfo;
                }
            }
        }

        /// <summary>
        /// The FormSelect_Configuration_FilAppFolder folder.
        /// </summary>
        [RepositoryFolder("1ccc7d83-b6fd-4ee0-87d4-50884a19487f")]
        public partial class FormSelect_Configuration_FilAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonopenInfo;
            RepoItemInfo _listitempci_adsi_xmlInfo;
            RepoItemInfo _listitemsim_xmlInfo;
            RepoItemInfo _listitemsff_sut_xmlInfo;
            RepoItemInfo _listitemcpci_sut_xmlInfo;
            RepoItemInfo _listitemultra16_sut_xmlInfo;

            /// <summary>
            /// Creates a new FormSelect_Configuration_Fil  folder.
            /// </summary>
            public FormSelect_Configuration_FilAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormSelect_Configuration_Fil", "/form[@title~'Select.*']", parentFolder, 30000, true, "1ccc7d83-b6fd-4ee0-87d4-50884a19487f")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "1ccc7d83-b6fd-4ee0-87d4-50884a19487f");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", 10000, null, "f3a0a435-ff64-47cf-87ec-ab7324a40668");
                _listitempci_adsi_xmlInfo = new RepoItemInfo(this, "ListItemPCI_ADSI_xml", ".//listitem[@accessiblename~'PCI_ADSI*']", 10000, null, "0f86702a-35f7-4029-87da-05cb41aa1876");
                _listitemsim_xmlInfo = new RepoItemInfo(this, "ListItemSIM_xml", ".//listitem[@accessiblename~'SIM.*']", 10000, null, "ec29feb2-69d4-4acb-906f-66a2149f390d");
                _listitemsff_sut_xmlInfo = new RepoItemInfo(this, "ListItemSFF_SUT_xml", ".//listitem[@accessiblename~'SFF_SUT*']", 10000, null, "fe55f265-5022-4a49-8ae1-ccf5034f2cc5");
                _listitemcpci_sut_xmlInfo = new RepoItemInfo(this, "ListItemCPCI_SUT_xml", ".//listitem[@accessiblename~'CPCI_SUT*']", 10000, null, "aad04d1a-c08e-4dcb-8465-95a12c981c6c");
                _listitemultra16_sut_xmlInfo = new RepoItemInfo(this, "ListItemUltra16_SUT_xml", ".//listitem[@accessiblename~'Ultra16*']", 10000, null, "9b32d074-a06a-4d1f-8a9b-8dee70f150bb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ccc7d83-b6fd-4ee0-87d4-50884a19487f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ccc7d83-b6fd-4ee0-87d4-50884a19487f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("f3a0a435-ff64-47cf-87ec-ab7324a40668")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("f3a0a435-ff64-47cf-87ec-ab7324a40668")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }

            /// <summary>
            /// The ListItemPCI_ADSI_xml item.
            /// </summary>
            [RepositoryItem("0f86702a-35f7-4029-87da-05cb41aa1876")]
            public virtual Ranorex.ListItem ListItemPCI_ADSI_xml
            {
                get
                {
                    return _listitempci_adsi_xmlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPCI_ADSI_xml item info.
            /// </summary>
            [RepositoryItemInfo("0f86702a-35f7-4029-87da-05cb41aa1876")]
            public virtual RepoItemInfo ListItemPCI_ADSI_xmlInfo
            {
                get
                {
                    return _listitempci_adsi_xmlInfo;
                }
            }

            /// <summary>
            /// The ListItemSIM_xml item.
            /// </summary>
            [RepositoryItem("ec29feb2-69d4-4acb-906f-66a2149f390d")]
            public virtual Ranorex.ListItem ListItemSIM_xml
            {
                get
                {
                    return _listitemsim_xmlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSIM_xml item info.
            /// </summary>
            [RepositoryItemInfo("ec29feb2-69d4-4acb-906f-66a2149f390d")]
            public virtual RepoItemInfo ListItemSIM_xmlInfo
            {
                get
                {
                    return _listitemsim_xmlInfo;
                }
            }

            /// <summary>
            /// The ListItemSFF_SUT_xml item.
            /// </summary>
            [RepositoryItem("fe55f265-5022-4a49-8ae1-ccf5034f2cc5")]
            public virtual Ranorex.ListItem ListItemSFF_SUT_xml
            {
                get
                {
                    return _listitemsff_sut_xmlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSFF_SUT_xml item info.
            /// </summary>
            [RepositoryItemInfo("fe55f265-5022-4a49-8ae1-ccf5034f2cc5")]
            public virtual RepoItemInfo ListItemSFF_SUT_xmlInfo
            {
                get
                {
                    return _listitemsff_sut_xmlInfo;
                }
            }

            /// <summary>
            /// The ListItemCPCI_SUT_xml item.
            /// </summary>
            [RepositoryItem("aad04d1a-c08e-4dcb-8465-95a12c981c6c")]
            public virtual Ranorex.ListItem ListItemCPCI_SUT_xml
            {
                get
                {
                    return _listitemcpci_sut_xmlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemCPCI_SUT_xml item info.
            /// </summary>
            [RepositoryItemInfo("aad04d1a-c08e-4dcb-8465-95a12c981c6c")]
            public virtual RepoItemInfo ListItemCPCI_SUT_xmlInfo
            {
                get
                {
                    return _listitemcpci_sut_xmlInfo;
                }
            }

            /// <summary>
            /// The ListItemUltra16_SUT_xml item.
            /// </summary>
            [RepositoryItem("9b32d074-a06a-4d1f-8a9b-8dee70f150bb")]
            public virtual Ranorex.ListItem ListItemUltra16_SUT_xml
            {
                get
                {
                    return _listitemultra16_sut_xmlInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemUltra16_SUT_xml item info.
            /// </summary>
            [RepositoryItemInfo("9b32d074-a06a-4d1f-8a9b-8dee70f150bb")]
            public virtual RepoItemInfo ListItemUltra16_SUT_xmlInfo
            {
                get
                {
                    return _listitemultra16_sut_xmlInfo;
                }
            }
        }

        /// <summary>
        /// The FormAccept_ConfigurationAppFolder folder.
        /// </summary>
        [RepositoryFolder("10b00ab7-bca8-4291-8248-c9b975b8daad")]
        public partial class FormAccept_ConfigurationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _textconfiguration_file_distrInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new FormAccept_Configuration  folder.
            /// </summary>
            public FormAccept_ConfigurationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormAccept_Configuration", "/form[@title='Accept Configuration']", parentFolder, 30000, true, "10b00ab7-bca8-4291-8248-c9b975b8daad")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "10b00ab7-bca8-4291-8248-c9b975b8daad");
                _textconfiguration_file_distrInfo = new RepoItemInfo(this, "TextConfiguration_File_Distr", ".//text[@accessiblename~'^Configuration\\ File\\ Distri']", 60000, null, "096ae5ce-6987-4ab8-b28b-486e1ebc5077");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", ".//button[@accessiblename='Ok']", 10000, null, "eb5d646c-8c6d-4e3a-849e-f097571ae1cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10b00ab7-bca8-4291-8248-c9b975b8daad")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10b00ab7-bca8-4291-8248-c9b975b8daad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextConfiguration_File_Distr item.
            /// </summary>
            [RepositoryItem("096ae5ce-6987-4ab8-b28b-486e1ebc5077")]
            public virtual Ranorex.Text TextConfiguration_File_Distr
            {
                get
                {
                    return _textconfiguration_file_distrInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextConfiguration_File_Distr item info.
            /// </summary>
            [RepositoryItemInfo("096ae5ce-6987-4ab8-b28b-486e1ebc5077")]
            public virtual RepoItemInfo TextConfiguration_File_DistrInfo
            {
                get
                {
                    return _textconfiguration_file_distrInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("eb5d646c-8c6d-4e3a-849e-f097571ae1cc")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("eb5d646c-8c6d-4e3a-849e-f097571ae1cc")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The FormUnsaved_ChangesAppFolder folder.
        /// </summary>
        [RepositoryFolder("f3488371-27c6-4a63-9297-f59c52198c93")]
        public partial class FormUnsaved_ChangesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonnoInfo;

            /// <summary>
            /// Creates a new FormUnsaved_Changes  folder.
            /// </summary>
            public FormUnsaved_ChangesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormUnsaved_Changes", "/form[@title='Unsaved Changes']", parentFolder, 30000, true, "f3488371-27c6-4a63-9297-f59c52198c93")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "f3488371-27c6-4a63-9297-f59c52198c93");
                _buttonnoInfo = new RepoItemInfo(this, "ButtonNo", ".//button[@accessiblename='No']", 10000, null, "7859a1b5-3887-44e1-b24f-d1e3a9c746d0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f3488371-27c6-4a63-9297-f59c52198c93")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f3488371-27c6-4a63-9297-f59c52198c93")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNo item.
            /// </summary>
            [RepositoryItem("7859a1b5-3887-44e1-b24f-d1e3a9c746d0")]
            public virtual Ranorex.Button ButtonNo
            {
                get
                {
                    return _buttonnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNo item info.
            /// </summary>
            [RepositoryItemInfo("7859a1b5-3887-44e1-b24f-d1e3a9c746d0")]
            public virtual RepoItemInfo ButtonNoInfo
            {
                get
                {
                    return _buttonnoInfo;
                }
            }
        }

    }
}
