///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.UISpecific.CriticalAreas
{
	/// <summary>
	/// The SafeCorridorExtrapolation recording.
	/// </summary>
	[TestModule("56296d3b-a071-4020-8255-e5e8621b771e", ModuleType.Recording, 1)]
	public partial class SafeCorridorExtrapolation : ITestModule
	{
		/// <summary>
		/// Holds an instance of the TacViewLib.TacViewLibRepositoryOverlays repository.
		/// </summary>
		public static TacViewLib.TacViewLibRepositoryOverlays repo = TacViewLib.TacViewLibRepositoryOverlays.Instance;

		static SafeCorridorExtrapolation instance = new SafeCorridorExtrapolation();

		/// <summary>
		/// Constructs a new instance.
		/// </summary>
		public SafeCorridorExtrapolation()
		{
		}

		/// <summary>
		/// Gets a static instance of this recording.
		/// </summary>
		public static SafeCorridorExtrapolation Instance
		{
			get { return instance; }
		}

#region Variables

#endregion

		/// <summary>
		/// Starts the replay of the static recording <see cref="Instance"/>.
		/// </summary>
		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.0")]
		public static void Start()
		{
			TestModuleRunner.Run(Instance);
		}

		/// <summary>
		/// Performs the playback of actions in this recording.
		/// </summary>
		/// <remarks>You should not call this method directly, instead pass the module
		/// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
		/// that will in turn invoke this method.</remarks>
		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.0")]
		void ITestModule.Run()
		{
			Mouse.DefaultMoveTime = 150;
			Keyboard.DefaultKeyPressTime = 25;
			Delay.SpeedFactor = 1.0;

			Init();

			ClearAllEvents();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2.ButtonSet_Range_to_500_km' at Center.", repo.FormTacViewC2.ButtonSet_Range_to_500_kmInfo, new RecordItemIndex(1));
			repo.FormTacViewC2.ButtonSet_Range_to_500_km.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ButtonZoom_Out' at Center.", repo.FormTacViewC2____map__Defaul.ButtonZoom_OutInfo, new RecordItemIndex(2));
			repo.FormTacViewC2____map__Defaul.ButtonZoom_Out.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ButtonZoom_Out' at Center.", repo.FormTacViewC2____map__Defaul.ButtonZoom_OutInfo, new RecordItemIndex(3));
			repo.FormTacViewC2____map__Defaul.ButtonZoom_Out.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ButtonZoom_Out' at Center.", repo.FormTacViewC2____map__Defaul.ButtonZoom_OutInfo, new RecordItemIndex(4));
			repo.FormTacViewC2____map__Defaul.ButtonZoom_Out.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.ButtonZoom_Out' at Center.", repo.FormTacViewC2____map__Defaul.ButtonZoom_OutInfo, new RecordItemIndex(5));
			repo.FormTacViewC2____map__Defaul.ButtonZoom_Out.Click();
			Delay.Milliseconds(0);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(8));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(9));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(10));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(11));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad6}{Decimal}{NumPad0}{NumPad4}{NumPad4}{Return}{Subtract}{NumPad6}{NumPad1}{Decimal}{NumPad3}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(12));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad6}{Decimal}{NumPad0}{NumPad4}{NumPad4}{Return}{Subtract}{NumPad6}{NumPad1}{Decimal}{NumPad3}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(13));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum1();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(17));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(18));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(19));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(20));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad6}{Decimal}{NumPad1}{NumPad5}{Return}{Subtract}{NumPad6}{NumPad1}{Decimal}{NumPad3}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(21));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad6}{Decimal}{NumPad1}{NumPad5}{Return}{Subtract}{NumPad6}{NumPad1}{Decimal}{NumPad3}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(22));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum2();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(26));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(27));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(28));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(29));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad5}{Decimal}{NumPad8}{NumPad5}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Decimal}{NumPad4}{NumPad8}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7 down}{NumPad0 down}{NumPad7 up}{NumPad0 up}'.", new RecordItemIndex(30));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad5}{Decimal}{NumPad8}{NumPad5}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Decimal}{NumPad4}{NumPad8}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7 down}{NumPad0 down}{NumPad7 up}{NumPad0 up}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(31));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum3();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(35));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(36));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(37));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(38));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad7}{Decimal}{NumPad8}{Return}{Subtract}{NumPad6}{NumPad1}{Decimal}{NumPad2}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(39));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad7}{Decimal}{NumPad8}{Return}{Subtract}{NumPad6}{NumPad1}{Decimal}{NumPad2}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(40));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum4();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(44));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(45));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(46));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(47));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad9 down}{Decimal down}{NumPad9 up}{Decimal up}{NumPad5}{NumPad2}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(48));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad9 down}{Decimal down}{NumPad9 up}{Decimal up}{NumPad5}{NumPad2}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(49));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum5();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(53));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(54));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(55));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(56));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad1 down}{NumPad0 down}{NumPad1 up}{NumPad0 up}{Decimal}{NumPad7}{NumPad5}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(57));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad1 down}{NumPad0 down}{NumPad1 up}{NumPad0 up}{Decimal}{NumPad7}{NumPad5}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(58));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum6();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(62));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(63));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(64));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(65));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{Decimal}{NumPad4}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Decimal}{NumPad1}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(66));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad2 up}{Decimal}{NumPad4}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Decimal}{NumPad1}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(67));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum7();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(71));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(72));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(73));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(74));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract down}{Subtract up}{NumPad1}{NumPad1}{Decimal}{NumPad8}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Decimal}{NumPad1}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(75));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract down}{Subtract up}{NumPad1}{NumPad1}{Decimal}{NumPad8}{Return}{Subtract}{NumPad6 down}{NumPad1 down}{NumPad6 up}{NumPad1 up}{Decimal}{NumPad1}{Return}{Return}{Return}{Return}{NumPad1}{NumPad0}{NumPad0}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(76));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum8();
			Delay.Milliseconds(150);
			
			GetTrackCount();
			Delay.Milliseconds(150);
			
			RandCoord();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemCreate_Track' at Center.", repo.FormRealView.MenuItemCreate_TrackInfo, new RecordItemIndex(80));
			repo.FormRealView.MenuItemCreate_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCreate_Track.MenuItemAir' at Center.", repo.FormCreate_Track.MenuItemAirInfo, new RecordItemIndex(81));
			repo.FormCreate_Track.MenuItemAir.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemLatitude' at CenterLeft.", repo.FormMainCreate.ListItemLatitudeInfo, new RecordItemIndex(82));
			repo.FormMainCreate.ListItemLatitude.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(83));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad1}{NumPad4}{Decimal}{NumPad2}{Return}{Subtract}{NumPad6}{NumPad2}{Return}{Return}{Return}{Return}{NumPad2}{NumPad5}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(84));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{Subtract}{NumPad1}{NumPad4}{Decimal}{NumPad2}{Return}{Subtract}{NumPad6}{NumPad2}{Return}{Return}{Return}{Return}{NumPad2}{NumPad5}{NumPad0}{Return}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(85));
			repo.FormMainCreate.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			GetTrackNum9();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormTacViewC2____map__Defaul.TextRealView' at Center.", repo.FormTacViewC2____map__Defaul.TextRealViewInfo, new RecordItemIndex(87));
			repo.FormTacViewC2____map__Defaul.TextRealView.Click();
			Delay.Milliseconds(0);
			
			KeyTrack9();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(89));
			Keyboard.Press(Keys.Return, 28, 100, 1, false);
			Delay.Milliseconds(50);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemEdit_Track' at Center.", repo.FormRealView.MenuItemEdit_TrackInfo, new RecordItemIndex(90));
			repo.FormRealView.MenuItemEdit_Track.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemTrue_Course' at CenterLeft.", repo.FormMainCreate.ListItemTrue_CourseInfo, new RecordItemIndex(91));
			repo.FormMainCreate.ListItemTrue_Course.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(92));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{NumPad0}{Return}'.", new RecordItemIndex(93));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(94));
			repo.FormMainCreate.ButtonSave.Click(125);
			Delay.Milliseconds(0);
			
			Delay.Duration(500, false);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonEdit_Track' at Center.", repo.FormMainCreate.ButtonEdit_TrackInfo, new RecordItemIndex(96));
			repo.FormMainCreate.ButtonEdit_Track.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemTrue_Course' at CenterLeft.", repo.FormMainCreate.ListItemTrue_CourseInfo, new RecordItemIndex(97));
			repo.FormMainCreate.ListItemTrue_Course.Click(Location.CenterLeft, 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(98));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{NumPad2}{NumPad7}{NumPad0}{Return}'.", new RecordItemIndex(99));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{NumPad2}{NumPad7}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(100));
			repo.FormMainCreate.ButtonSave.Click(125);
			Delay.Milliseconds(0);
			
			Delay.Duration(500, false);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonEdit_Track' at Center.", repo.FormMainCreate.ButtonEdit_TrackInfo, new RecordItemIndex(102));
			repo.FormMainCreate.ButtonEdit_Track.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ListItemTrue_Course' at CenterLeft.", repo.FormMainCreate.ListItemTrue_CourseInfo, new RecordItemIndex(103));
			repo.FormMainCreate.ListItemTrue_Course.Click(Location.CenterLeft, 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(104));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{End}{LShiftKey down}{Home}{LShiftKey up}{NumPad1 down}{NumPad8 down}{NumPad1 up}{NumPad8 up}{NumPad0}{Return}'.", new RecordItemIndex(105));
			Keyboard.Press("{End}{LShiftKey down}{Home}{LShiftKey up}{NumPad1 down}{NumPad8 down}{NumPad1 up}{NumPad8 up}{NumPad0}{Return}", 100);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonSave' at Center.", repo.FormMainCreate.ButtonSaveInfo, new RecordItemIndex(106));
			repo.FormMainCreate.ButtonSave.Click(125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMainCreate.ButtonCLOSE' at Center.", repo.FormMainCreate.ButtonCLOSEInfo, new RecordItemIndex(107));
			repo.FormMainCreate.ButtonCLOSE.Click(125);
			Delay.Milliseconds(0);
			
			DropTrackNum9();
			Delay.Milliseconds(0);
			
			Delay.Duration(450000, false);
			
			ValidateAlertsForTrack1();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack2();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack3();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack4();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack5();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack6();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack7();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack8();
			Delay.Milliseconds(0);
			
			ValidateAlertsForTrack9();
			Delay.Milliseconds(0);
			
			DropTrackNum1();
			Delay.Milliseconds(0);
			
			DropTrackNum2();
			Delay.Milliseconds(0);
			
			DropTrackNum3();
			Delay.Milliseconds(0);
			
			DropTrackNum4();
			Delay.Milliseconds(0);
			
			DropTrackNum5();
			Delay.Milliseconds(0);
			
			DropTrackNum6();
			Delay.Milliseconds(0);
			
			DropTrackNum7();
			Delay.Milliseconds(0);
			
			DropTrackNum8();
			Delay.Milliseconds(0);
			
			DeleteAllOverlays();
			Delay.Milliseconds(0);
			
			TurnOnInterfaceTwo();
			Delay.Milliseconds(0);
			
		}

#region Image Feature Data
#endregion
	}
}
