///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace SystemManagerLib.UISpecific.DXview
{
    /// <summary>
    /// The TurnOnDX recording.
    /// </summary>
    [TestModule("b8f885a7-0aaa-4671-bda4-a38425d2c4c4", ModuleType.Recording, 1)]
    public partial class TurnOnDX : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SystemManagerLib.V15SmokeTestRepository repository.
        /// </summary>
        public static SystemManagerLib.V15SmokeTestRepository repo = SystemManagerLib.V15SmokeTestRepository.Instance;

        static TurnOnDX instance = new TurnOnDX();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TurnOnDX()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TurnOnDX Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 250;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.TitleBarSystem_Manager___UNCLASS' at Center.", repo.FormSystem_Manager___UNCLASS.TitleBarSystem_Manager___UNCLASSInfo, new RecordItemIndex(0));
            repo.FormSystem_Manager___UNCLASS.TitleBarSystem_Manager___UNCLASS.Click(300);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.TabPageDXControl' at Center.", repo.FormSystem_Manager___UNCLASS.TabPageDXControlInfo, new RecordItemIndex(1));
            repo.FormSystem_Manager___UNCLASS.TabPageDXControl.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ButtonLaunch_DX_View' at Center.", repo.FormSystem_Manager___UNCLASS.ButtonLaunch_DX_ViewInfo, new RecordItemIndex(2));
            repo.FormSystem_Manager___UNCLASS.ButtonLaunch_DX_View.Click(300);
            Delay.Milliseconds(840);
            
            Ensure_Enabled();
            Delay.Milliseconds(250);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ElementSm.TextC2_Host' at Center.", repo.FormSystem_Manager___UNCLASS.ElementSm.TextC2_HostInfo, new RecordItemIndex(4));
            repo.FormSystem_Manager___UNCLASS.ElementSm.TextC2_Host.Click(300);
            Delay.Milliseconds(840);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}{Down}{Tab}{Down}{Tab}{Down}{Tab}{Down}'.", new RecordItemIndex(5));
            Keyboard.Press("{Tab}{Down}{Tab}{Down}{Tab}{Down}{Tab}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ElementSm.TextSet_All_Links' at Center.", repo.FormSystem_Manager___UNCLASS.ElementSm.TextSet_All_LinksInfo, new RecordItemIndex(6));
            repo.FormSystem_Manager___UNCLASS.ElementSm.TextSet_All_Links.Click(300);
            Delay.Milliseconds(800);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}'.", new RecordItemIndex(7));
            Keyboard.Press("{Down}{Return}");
            Delay.Milliseconds(50);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ElementSm.TextSet_All_Links1' at Center.", repo.FormSystem_Manager___UNCLASS.ElementSm.TextSet_All_Links1Info, new RecordItemIndex(8));
            repo.FormSystem_Manager___UNCLASS.ElementSm.TextSet_All_Links1.Click(300);
            Delay.Milliseconds(850);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}'.", new RecordItemIndex(9));
            Keyboard.Press("{Down}{Return}");
            Delay.Milliseconds(50);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormSystem_Manager___UNCLASS.ButtonApply' at Center.", repo.FormSystem_Manager___UNCLASS.ButtonApplyInfo, new RecordItemIndex(10));
            repo.FormSystem_Manager___UNCLASS.ButtonApply.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TitleBarDxView1'.", repo.TitleBarDxView1Info, new RecordItemIndex(11));
            Validate.Exists(repo.TitleBarDxView1Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TitleBarDxView1' at Center.", repo.TitleBarDxView1Info, new RecordItemIndex(12));
            repo.TitleBarDxView1.Click(150);
            Delay.Milliseconds(100);
            
            ScreenshotRecName();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
}
