///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.LinkSpecific.Surveillance.Land.ValidateTrack
{
    /// <summary>
    /// The ValidateLandTrack6016D recording.
    /// </summary>
    [TestModule("88f93556-a6d9-4446-b8a8-5795f9bfad76", ModuleType.Recording, 1)]
    public partial class ValidateLandTrack6016D : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TacViewLib.TacViewLibRepository repository.
        /// </summary>
        public static TacViewLib.TacViewLibRepository repo = TacViewLib.TacViewLibRepository.Instance;

        static ValidateLandTrack6016D instance = new ValidateLandTrack6016D();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateLandTrack6016D()
        {
            PlatN = "1";
            Plat = "Troop Concentration/Unit";
            ActN = "1";
            Act = "Holding";
            StypeN = "1";
            Stype = "TOW";
            tracknumber = "";
            Connection1 = "";
            Connection2 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateLandTrack6016D Instance
        {
            get { return instance; }
        }

#region Variables

        string _PlatN;

        /// <summary>
        /// Gets or sets the value of variable PlatN.
        /// </summary>
        [TestVariable("0916bd88-142a-4ebd-a6ce-d70862854df6")]
        public string PlatN
        {
            get { return _PlatN; }
            set { _PlatN = value; }
        }

        string _Plat;

        /// <summary>
        /// Gets or sets the value of variable Plat.
        /// </summary>
        [TestVariable("3f2c7616-735b-4bf9-bb2f-2f435da42209")]
        public string Plat
        {
            get { return _Plat; }
            set { _Plat = value; }
        }

        string _ActN;

        /// <summary>
        /// Gets or sets the value of variable ActN.
        /// </summary>
        [TestVariable("8119ebab-9687-4605-9a76-f13a39d041a0")]
        public string ActN
        {
            get { return _ActN; }
            set { _ActN = value; }
        }

        string _Act;

        /// <summary>
        /// Gets or sets the value of variable Act.
        /// </summary>
        [TestVariable("37bbdfaa-309e-4311-ae9a-e10b72251f80")]
        public string Act
        {
            get { return _Act; }
            set { _Act = value; }
        }

        string _StypeN;

        /// <summary>
        /// Gets or sets the value of variable StypeN.
        /// </summary>
        [TestVariable("20a1dad7-423a-417e-9f47-77216aefba9a")]
        public string StypeN
        {
            get { return _StypeN; }
            set { _StypeN = value; }
        }

        string _Stype;

        /// <summary>
        /// Gets or sets the value of variable Stype.
        /// </summary>
        [TestVariable("39596aa0-cf0e-487a-acb2-a3df0b2bca6f")]
        public string Stype
        {
            get { return _Stype; }
            set { _Stype = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable tracknumber.
        /// </summary>
        [TestVariable("7d32a69b-dcdf-4d89-a20e-00ecbbbba328")]
        public string tracknumber
        {
            get { return repo.tracknumber; }
            set { repo.tracknumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Connection1.
        /// </summary>
        [TestVariable("2fc347bc-880f-424d-939c-f855be60595d")]
        public string Connection1
        {
            get { return repo.Connection1; }
            set { repo.Connection1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Connection2.
        /// </summary>
        [TestVariable("f6d22605-e75b-4fd9-ae07-943d4d0d6a79")]
        public string Connection2
        {
            get { return repo.Connection2; }
            set { repo.Connection2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 250;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2000ms.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            SetTrackNumberInRepo();
            Delay.Milliseconds(0);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            ViewTrackProperties();
            Delay.Milliseconds(0);
            
            ValidateInd();
            Delay.Milliseconds(0);
            
            ValidateID();
            Delay.Milliseconds(0);
            
            ValidatePlat();
            Delay.Milliseconds(0);
            
            ValidateAct();
            Delay.Milliseconds(0);
            
            ValidateStype();
            Delay.Milliseconds(0);
            
            ValidateHAE();
            Delay.Milliseconds(0);
            
            ValidateAOPcs();
            Delay.Milliseconds(0);
            
            ValidateMajorAxis3();
            Delay.Milliseconds(0);
            
            ValidateMinorAxis3();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMain__Land_Point_Track_TN.ButtonCLOSE' at Center.", repo.FormMain__Land_Point_Track_TN.ButtonCLOSEInfo, new RecordItemIndex(13));
            repo.FormMain__Land_Point_Track_TN.ButtonCLOSE.Click();
            Delay.Milliseconds(0);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            DropTrack();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2000ms.", new RecordItemIndex(16));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
}
