///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.LinkSpecific.C2AirControl.Handovers
{
    /// <summary>
    /// The HandoverSingleTrack recording.
    /// </summary>
    [TestModule("7eb02c0e-e2b1-40d1-8556-390cdb9f245e", ModuleType.Recording, 1)]
    public partial class HandoverSingleTrack : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TacViewLib.Link_16_RegressionRepository repository.
        /// </summary>
        public static TacViewLib.Link_16_RegressionRepository repo = TacViewLib.Link_16_RegressionRepository.Instance;

        static HandoverSingleTrack instance = new HandoverSingleTrack();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HandoverSingleTrack()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HandoverSingleTrack Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable connection1.
        /// </summary>
        [TestVariable("5d4e3e56-3172-4cd7-82e9-644dce97207c")]
        public string connection1
        {
            get { return repo.connection1; }
            set { repo.connection1 = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable tracknumber.
        /// </summary>
        [TestVariable("434ed62d-b00e-4df9-a045-0a1b6f6c92e7")]
        public string tracknumber
        {
            get { return repo.tracknumber; }
            set { repo.tracknumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ownunit.
        /// </summary>
        [TestVariable("ae53e9c2-51e5-48e8-a15d-34d6d9b55ce6")]
        public string ownunit
        {
            get { return repo.ownunit; }
            set { repo.ownunit = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 250;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2000ms.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            GetUnitNumbers();
            Delay.Milliseconds(0);
            
            CreateTrackRepoItems();
            Delay.Milliseconds(250);
            
            RightClickTrack();
            Delay.Milliseconds(250);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemTrackNumber' at Center.", repo.FormRealView.MenuItemTrackNumberInfo, new RecordItemIndex(4));
            repo.FormRealView.MenuItemTrackNumber.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormConnection1.MenuItemCommands' at Center.", repo.FormConnection1.MenuItemCommandsInfo, new RecordItemIndex(5));
            repo.FormConnection1.MenuItemCommands.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCommands.MenuItemControl__J10_3___J10_5_' at Center.", repo.FormCommands.MenuItemControl__J10_3___J10_5_Info, new RecordItemIndex(6));
            repo.FormCommands.MenuItemControl__J10_3___J10_5_.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormControl.MenuItemAssume_Control__J10_5___' at Center.", repo.FormControl.MenuItemAssume_Control__J10_5___Info, new RecordItemIndex(7));
            repo.FormControl.MenuItemAssume_Control__J10_5___.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form_Assume_Control.ButtonSave' at Center.", repo.Form_Assume_Control.ButtonSaveInfo, new RecordItemIndex(8));
            repo.Form_Assume_Control.ButtonSave.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3000ms.", new RecordItemIndex(9));
            Delay.Duration(3000, false);
            
            RightClickTrack();
            Delay.Milliseconds(0);
            
            ViewTrackPropertiesC2Host2();
            Delay.Milliseconds(0);
            
            SetUnit1CU();
            Delay.Milliseconds(0);
            
            Validate_CU();
            Delay.Milliseconds(250);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormMain__Air_TN.ButtonCLOSE' at Center.", repo.FormMain__Air_TN.ButtonCLOSEInfo, new RecordItemIndex(14));
            repo.FormMain__Air_TN.ButtonCLOSE.Click(150);
            Delay.Milliseconds(100);
            
            RightClickTrack();
            Delay.Milliseconds(250);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormRealView.MenuItemConnection1' at Center.", repo.FormRealView.MenuItemConnection1Info, new RecordItemIndex(16));
            repo.FormRealView.MenuItemConnection1.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormConnection1.MenuItemCommands' at Center.", repo.FormConnection1.MenuItemCommandsInfo, new RecordItemIndex(17));
            repo.FormConnection1.MenuItemCommands.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCommands.MenuItemControl__J10_3___J10_5_' at Center.", repo.FormCommands.MenuItemControl__J10_3___J10_5_Info, new RecordItemIndex(18));
            repo.FormCommands.MenuItemControl__J10_3___J10_5_.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormControl.MenuItemHandover_Control__J10_3_' at Center.", repo.FormControl.MenuItemHandover_Control__J10_3_Info, new RecordItemIndex(19));
            repo.FormControl.MenuItemHandover_Control__J10_3_.Click(150);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form_Handover_Control.ListItemAddressee_Track_Number' at CenterLeft.", repo.Form_Handover_Control.ListItemAddressee_Track_NumberInfo, new RecordItemIndex(20));
            repo.Form_Handover_Control.ListItemAddressee_Track_Number.Click(Location.CenterLeft, 150);
            Delay.Milliseconds(100);
            
            EnterUnit2();
            Delay.Milliseconds(250);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form_Handover_Control.ButtonSave' at Center.", repo.Form_Handover_Control.ButtonSaveInfo, new RecordItemIndex(22));
            repo.Form_Handover_Control.ButtonSave.Click(100);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FormRealView1.PictureGraphic'.", repo.FormRealView1.PictureGraphicInfo, new RecordItemIndex(23));
            Validate.Exists(repo.FormRealView1.PictureGraphicInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
}
