///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.LinkSpecific.Surveillance.Reference.CreateTrack
{
	/// <summary>
	/// The CreateTrack recording.
	/// </summary>
	public partial class CreateNoStatementTOAD1
	{
		public static string Ptype = "Hazard";
		public static string Amp = "Missile Launch Point";
		public static string EnvCat = "Space";
		public static string ECAmp = "Nuclear Warhead";
		public static string SpTrk;
		
		//************************************************************************************//
		//***********************Enters Related TN # of Space Track***************************//
		//************************************************************************************//
		
		public static void RelatedTN()
		{
			//Your code here. Code inside this method will not be changed by the code generator.
			Report.Info("Key sequence 'SpTrk'.");
			Keyboard.Press(SpTrk);
		}
		
		//************************************************************************************//
		//********************Validates previous track wass dropped***************************//
		//************************************************************************************//
		
		public static void ValidateDropTrack()
		{
		if (repo.FormTacViewC2____map__Pacifi1.PictureDropTrack1Info.Exists())
			{
				TacViewLib.LinkSpecific.Surveillance.Drop_Track.DropTrack.Start();
			}
		}
	

		static CreateNoStatementTOAD1()
		{
			//Your recording specific initialization code goes here.
		}

	}
}
