///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.LinkSpecific.Surveillance.Reference_NoStatements.CreateTrack
{
	/// <summary>
	/// The CreateTrack recording.
	/// </summary>
	
	
		//************************************************************************************//
		//**************Default values to enter for track if csv file not present*************//
		//************************************************************************************//
	
	public partial class CreateResetNoStatementTOAD1
	{
		public static string PT = "Hazard";
		public static string Amp = "Impact Point";
		public static string EC = "Space";
		public static string ECAmp = "Warhead";
		public static string TF = "ARRIVAL TIME";
		
        
		//************************************************************************************//
		//***************************Enters Point Type Value**********************************//
		//************************************************************************************//
		
		public void PTval()
		{
			Keyboard.Press("{LMenu down}{Down}{LMenu up}");
	       	foreach( ListItem item in repo.ListRealView.Self.Items )
        	{
           		if ( item.Text == PT )
           		{
            	item.Select();
            	item.Click();
               	break;        
           		}           		
        	}
		}
		
		//************************************************************************************//
		//***************************Enters Amplification Value*******************************//
		//************************************************************************************//
		
		public void Ampval()
		{
			Keyboard.Press("{LMenu down}{Down}{LMenu up}");
	       	foreach( ListItem item in repo.ListRealView.Self.Items )
        	{
           		if ( item.Text == Amp )
           		{
            	item.Select();
            	item.Click();
               	break;        
           		}           		
        	}
		}

		//************************************************************************************//
		//***********************Enters Environment Category Value****************************//
		//************************************************************************************//
		
		public void ECval()
		{
			Keyboard.Press("{LMenu down}{Down}{LMenu up}");
	       	foreach( ListItem item in repo.ListRealView.Self.Items )
        	{
           		if ( item.Text == EC )
           		{
            	item.Select();
            	item.Click();
               	break;        
           		}           		
        	}
		}

		//************************************************************************************//
		//******************Enters Environment Category Amplification Value*******************//
		//************************************************************************************//
		
		public void ECampval()
		{
			Keyboard.Press("{LMenu down}{Down}{LMenu up}");
	       	foreach( ListItem item in repo.ListRealView.Self.Items )
        	{
           		if ( item.Text == ECAmp )
           		{
            	item.Select();
            	item.Click();
               	break;        
           		}           		
        	}
		}
		
		//************************************************************************************//
		//*****************************Enters Time Function Value*****************************//
		//************************************************************************************//
		
		public void TFval()
		{
			Keyboard.Press("{LMenu down}{Down}{LMenu up}");
	       	foreach( ListItem item in repo.ListRealView.Self.Items )
        	{
           		if ( item.Text == TF )
           		{
            	item.Select();
            	item.Click();
               	break;        
           		}           		
        	}
		}		
		
		//************************************************************************************//
		//********************Validates the created track is dropped**************************//
		//************************************************************************************//
		
		public void ValidateDropTrack()
		{
		Delay.Milliseconds(1500, false);
		if (repo.FormTacViewC2.PictureTrackCreateDropInfo.Exists())
			{
				TacViewLib.LinkSpecific.Surveillance.Drop_Track.DropTrack.Start();
			}
		}

		static CreateResetNoStatementTOAD1()
		{
			//Your recording specific initialization code goes here.
		}

		private void Init()
		{
			// Your recording specific initialization code goes here.
		}
	}
}