///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.UISpecific.TrackActions
{
	/// <summary>
	/// The AirTrack recording.
	/// </summary>
	public partial class AirTrack
	{
		public Track myAirTrack;
		
		public void CreateTrack()
		{
			myAirTrack = new Track("air", true);
		}
		
		public void RightClickTrack()
		{
			myAirTrack.RightClickTrack(MouseButtons.Right);
		}

		static AirTrack()
		{
			//Your recording specific initialization code goes here.
		}

		public void Cleanup()
		{
			myAirTrack = null;
		}
		
		public void ValidateTrack()
		{
			myAirTrack.ValidateTrackAccessible(true);
		}

		public void ValidateTrackNotExists()
		{
			myAirTrack.ValidateTrackAccessible(false);			
		}
	}
}
