///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.UISpecific.Setup_2_Toad_Interfaces
{
	/// <summary>
	/// The Recording1 recording.
	/// </summary>
	public partial class HideNS
	{
		public void Validate_NS_Not_Enabled()
		{
			if  (repo.FormPreferences.CheckBoxDisplay_No_Statement_val.Checked)
			{
				repo.FormPreferences.CheckBoxDisplay_No_Statement_val.Click();
			}
		
			else return;
		
		}

		static HideNS()
		{
			//Your recording specific initialization code goes here.
		}

		public void TransparencyOff()
		{
			if  (repo.FormPreferences.CheckBoxTransparency.Checked)
			{
				repo.FormPreferences.CheckBoxTransparency.Click();
			}
		
			else return;
		
		}

		public void CloseOld()
		{
			if (repo.FormTrackProperties.ButtonCLOSEInfo.Exists())
				{
				Report.Info("Track Properties window found, closing now");
				repo.FormTrackProperties.ButtonCLOSE.Click();
				}
		}

		public void UserCodeMethod1()
		{
			CommonUtilLib.Util SharedFunctions = new CommonUtilLib.Util();
			SharedFunctions.TADILJ_TN();
			
		}

		public void UserCodeMethod2()
		{
			CommonUtilLib.Util SharedFunctions = new CommonUtilLib.Util();
			SharedFunctions.ATDL1_TN();
			
		}

		private void Init()
		{
			// Your recording specific initialization code goes here.
		}
	}
}
