///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TacViewLib
{
    /// <summary>
    /// The class representing the TacViewSustainment_DefectsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.1.1"), RepositoryFolder("47f7b833-457d-4fa4-b96b-b0a1bc9771f4")]
    public partial class TacViewSustainment_DefectsRepository : RepoGenBaseFolder
    {
        static TacViewSustainment_DefectsRepository instance = new TacViewSustainment_DefectsRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TacViewSustainment_DefectsRepository element repository.
        /// </summary>
        [RepositoryFolder("47f7b833-457d-4fa4-b96b-b0a1bc9771f4")]
        public static TacViewSustainment_DefectsRepository Instance {
            get { return instance; }
        }

        TacViewSustainment_DefectsRepositoryFolders.FormRealViewAppFolder _formrealview;
        TacViewSustainment_DefectsRepositoryFolders.FormTacViewC2AppFolder _formtacviewc2;
        TacViewSustainment_DefectsRepositoryFolders.FormCreate_TrackAppFolder _formcreate_track;
        TacViewSustainment_DefectsRepositoryFolders.FormC2_HOSTAppFolder _formc2_host;
        TacViewSustainment_DefectsRepositoryFolders.FormMain__SubSurface_CreateAppFolder _formmain__subsurface_create;
        TacViewSustainment_DefectsRepositoryFolders.ListRealViewAppFolder _listrealview;
        TacViewSustainment_DefectsRepositoryFolders.FormMain__SubSurface_PropAppFolder _formmain__subsurface_prop;
        TacViewSustainment_DefectsRepositoryFolders.FormTracksAppFolder _formtracks;
        TacViewSustainment_DefectsRepositoryFolders.FormRealView1AppFolder _formrealview1;
        TacViewSustainment_DefectsRepositoryFolders.FormC2_HOST_2AppFolder _formc2_host_2;
        TacViewSustainment_DefectsRepositoryFolders.RealViewDialogAppFolder _realviewdialog;
        TacViewSustainment_DefectsRepositoryFolders.FormMain__Reference_Point_TNAppFolder _formmain__reference_point_tn;
        TacViewSustainment_DefectsRepositoryFolders.FormTOAD2AppFolder _formtoad2;
        TacViewSustainment_DefectsRepositoryFolders.FormMain__Reference_Point_TNPropAppFolder _formmain__reference_point_tnprop;
        TacViewSustainment_DefectsRepositoryFolders.FormMainAppFolder _formmain;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TacViewSustainment_DefectsRepository() : base("TacViewSustainment_DefectsRepository", "", null, 30000, false)
        {
            _formrealview = new TacViewSustainment_DefectsRepositoryFolders.FormRealViewAppFolder(this);
            _formtacviewc2 = new TacViewSustainment_DefectsRepositoryFolders.FormTacViewC2AppFolder(this);
            _formcreate_track = new TacViewSustainment_DefectsRepositoryFolders.FormCreate_TrackAppFolder(this);
            _formc2_host = new TacViewSustainment_DefectsRepositoryFolders.FormC2_HOSTAppFolder(this);
            _formmain__subsurface_create = new TacViewSustainment_DefectsRepositoryFolders.FormMain__SubSurface_CreateAppFolder(this);
            _listrealview = new TacViewSustainment_DefectsRepositoryFolders.ListRealViewAppFolder(this);
            _formmain__subsurface_prop = new TacViewSustainment_DefectsRepositoryFolders.FormMain__SubSurface_PropAppFolder(this);
            _formtracks = new TacViewSustainment_DefectsRepositoryFolders.FormTracksAppFolder(this);
            _formrealview1 = new TacViewSustainment_DefectsRepositoryFolders.FormRealView1AppFolder(this);
            _formc2_host_2 = new TacViewSustainment_DefectsRepositoryFolders.FormC2_HOST_2AppFolder(this);
            _realviewdialog = new TacViewSustainment_DefectsRepositoryFolders.RealViewDialogAppFolder(this);
            _formmain__reference_point_tn = new TacViewSustainment_DefectsRepositoryFolders.FormMain__Reference_Point_TNAppFolder(this);
            _formtoad2 = new TacViewSustainment_DefectsRepositoryFolders.FormTOAD2AppFolder(this);
            _formmain__reference_point_tnprop = new TacViewSustainment_DefectsRepositoryFolders.FormMain__Reference_Point_TNPropAppFolder(this);
            _formmain = new TacViewSustainment_DefectsRepositoryFolders.FormMainAppFolder(this);
        }

#region Variables

        string _TrackNum = "2070";

        /// <summary>
        /// Gets or sets the value of variable TrackNum.
        /// </summary>
        [TestVariable("acdd2bf1-74be-462e-b0ad-411b18a9fe04")]
        public string TrackNum
        {
            get { return _TrackNum; }
            set { _TrackNum = value; }
        }

#endregion

        /// <summary>
        /// The FormRealView folder.
        /// </summary>
        [RepositoryFolder("fece601b-2c95-4923-a610-1019bf531517")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormRealViewAppFolder FormRealView
        {
            get { return _formrealview; }
        }

        /// <summary>
        /// The FormTacViewC2 folder.
        /// </summary>
        [RepositoryFolder("a49355b1-fba5-464a-8ab0-957823894aef")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormTacViewC2AppFolder FormTacViewC2
        {
            get { return _formtacviewc2; }
        }

        /// <summary>
        /// The FormCreate_Track folder.
        /// </summary>
        [RepositoryFolder("b08f6db2-42d8-4894-94cf-ffa96ef59cdb")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormCreate_TrackAppFolder FormCreate_Track
        {
            get { return _formcreate_track; }
        }

        /// <summary>
        /// The FormC2_HOST folder.
        /// </summary>
        [RepositoryFolder("76d3d058-4a3b-439f-9042-a25044c47822")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormC2_HOSTAppFolder FormC2_HOST
        {
            get { return _formc2_host; }
        }

        /// <summary>
        /// The FormMain__SubSurface_Create folder.
        /// </summary>
        [RepositoryFolder("fc4a2a3c-8caa-4d6f-be58-208da013154d")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormMain__SubSurface_CreateAppFolder FormMain__SubSurface_Create
        {
            get { return _formmain__subsurface_create; }
        }

        /// <summary>
        /// The ListRealView folder.
        /// </summary>
        [RepositoryFolder("1cb04e6e-e4ac-49c7-b5e8-4f13a601ae3b")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.ListRealViewAppFolder ListRealView
        {
            get { return _listrealview; }
        }

        /// <summary>
        /// The FormMain__SubSurface_Prop folder.
        /// </summary>
        [RepositoryFolder("9da2a2bc-1cb3-49ec-895f-a526f8d1ffe9")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormMain__SubSurface_PropAppFolder FormMain__SubSurface_Prop
        {
            get { return _formmain__subsurface_prop; }
        }

        /// <summary>
        /// The FormTracks folder.
        /// </summary>
        [RepositoryFolder("709eae15-d818-40e1-bf53-8fffc9fcb44b")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormTracksAppFolder FormTracks
        {
            get { return _formtracks; }
        }

        /// <summary>
        /// The FormRealView1 folder.
        /// </summary>
        [RepositoryFolder("5b2ad949-bc93-4a8b-87e8-b28c44c77998")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormRealView1AppFolder FormRealView1
        {
            get { return _formrealview1; }
        }

        /// <summary>
        /// The FormC2_HOST_2 folder.
        /// </summary>
        [RepositoryFolder("f72c0a25-e193-473a-83ea-a0fd2b52ff98")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormC2_HOST_2AppFolder FormC2_HOST_2
        {
            get { return _formc2_host_2; }
        }

        /// <summary>
        /// The RealViewDialog folder.
        /// </summary>
        [RepositoryFolder("b95f943f-5f28-47cc-9bf7-6820c167cce3")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.RealViewDialogAppFolder RealViewDialog
        {
            get { return _realviewdialog; }
        }

        /// <summary>
        /// The FormMain__Reference_Point_TN folder.
        /// </summary>
        [RepositoryFolder("1ff358b2-8ad3-4bbd-b9db-7aec15063e61")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormMain__Reference_Point_TNAppFolder FormMain__Reference_Point_TN
        {
            get { return _formmain__reference_point_tn; }
        }

        /// <summary>
        /// The FormTOAD2 folder.
        /// </summary>
        [RepositoryFolder("f854273f-73ce-456e-8a86-dd38490a2a31")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormTOAD2AppFolder FormTOAD2
        {
            get { return _formtoad2; }
        }

        /// <summary>
        /// The FormMain__Reference_Point_TNProp folder.
        /// </summary>
        [RepositoryFolder("9f48873c-eabe-4f58-a403-54cd0ec65b38")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormMain__Reference_Point_TNPropAppFolder FormMain__Reference_Point_TNProp
        {
            get { return _formmain__reference_point_tnprop; }
        }

        /// <summary>
        /// The FormMain folder.
        /// </summary>
        [RepositoryFolder("160fa4ee-ce39-499c-8b4d-396f3d7c58ae")]
        public virtual TacViewSustainment_DefectsRepositoryFolders.FormMainAppFolder FormMain
        {
            get { return _formmain; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class TacViewSustainment_DefectsRepositoryFolders
    {
        /// <summary>
        /// The FormRealViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("fece601b-2c95-4923-a610-1019bf531517")]
        public partial class FormRealViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemcreate_trackInfo;
            RepoItemInfo _menuitemtracknumber2Info;
            RepoItemInfo _menuitemtracknumberInfo;
            RepoItemInfo _menuitemtracksInfo;
            RepoItemInfo _menuitemdrop_trackInfo;

            /// <summary>
            /// Creates a new FormRealView  folder.
            /// </summary>
            public FormRealViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormRealView", "/form[@title='' and @processname='RealView' and @class='Afx:00400000:808:00010011:00000000:00000000']", parentFolder, 30000, true, "fece601b-2c95-4923-a610-1019bf531517")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "fece601b-2c95-4923-a610-1019bf531517");
                _menuitemcreate_trackInfo = new RepoItemInfo(this, "MenuItemCreate_Track", "contextmenu[1]/menuitem[@accessiblename='Create Track']", 10000, null, "12e55e16-3997-4d92-ad24-aa1418e95438");
                _menuitemtracknumber2Info = new RepoItemInfo(this, "MenuItemTrackNumber2", "contextmenu[1]/menuitem[@accessiblename='C2 HOST 2 Track#'+$tracknum or @accessiblename='TOAD 2 Track#'+$tracknum]", 10000, null, "1b08b549-4d9c-46c3-84e6-ac26f81b75b0");
                _menuitemtracknumberInfo = new RepoItemInfo(this, "MenuItemTrackNumber", "contextmenu[1]/menuitem[@accessiblename='C2 HOST Track#'+$tracknum or @accessiblename='TOAD Track #'+$tracknum]", 10000, null, "94ee4de4-817e-44c4-a659-16506d53e92b");
                _menuitemtracksInfo = new RepoItemInfo(this, "MenuItemTracks", "contextmenu[1]/menuitem[@accessiblename='Tracks']", 10000, null, "fceb6506-2e2c-414f-a795-852d917f319e");
                _menuitemdrop_trackInfo = new RepoItemInfo(this, "MenuItemDrop_Track", "contextmenu[1]/menuitem[@accessiblename='Drop Track']", 10000, null, "1a1ef495-35fd-45f8-9e49-b15bb41f4464");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fece601b-2c95-4923-a610-1019bf531517")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fece601b-2c95-4923-a610-1019bf531517")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemCreate_Track item.
            /// </summary>
            [RepositoryItem("12e55e16-3997-4d92-ad24-aa1418e95438")]
            public virtual Ranorex.MenuItem MenuItemCreate_Track
            {
                get
                {
                    return _menuitemcreate_trackInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemCreate_Track item info.
            /// </summary>
            [RepositoryItemInfo("12e55e16-3997-4d92-ad24-aa1418e95438")]
            public virtual RepoItemInfo MenuItemCreate_TrackInfo
            {
                get
                {
                    return _menuitemcreate_trackInfo;
                }
            }

            /// <summary>
            /// The MenuItemTrackNumber2 item.
            /// </summary>
            [RepositoryItem("1b08b549-4d9c-46c3-84e6-ac26f81b75b0")]
            public virtual Ranorex.MenuItem MenuItemTrackNumber2
            {
                get
                {
                    return _menuitemtracknumber2Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemTrackNumber2 item info.
            /// </summary>
            [RepositoryItemInfo("1b08b549-4d9c-46c3-84e6-ac26f81b75b0")]
            public virtual RepoItemInfo MenuItemTrackNumber2Info
            {
                get
                {
                    return _menuitemtracknumber2Info;
                }
            }

            /// <summary>
            /// The MenuItemTrackNumber item.
            /// </summary>
            [RepositoryItem("94ee4de4-817e-44c4-a659-16506d53e92b")]
            public virtual Ranorex.MenuItem MenuItemTrackNumber
            {
                get
                {
                    return _menuitemtracknumberInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemTrackNumber item info.
            /// </summary>
            [RepositoryItemInfo("94ee4de4-817e-44c4-a659-16506d53e92b")]
            public virtual RepoItemInfo MenuItemTrackNumberInfo
            {
                get
                {
                    return _menuitemtracknumberInfo;
                }
            }

            /// <summary>
            /// The MenuItemTracks item.
            /// </summary>
            [RepositoryItem("fceb6506-2e2c-414f-a795-852d917f319e")]
            public virtual Ranorex.MenuItem MenuItemTracks
            {
                get
                {
                    return _menuitemtracksInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemTracks item info.
            /// </summary>
            [RepositoryItemInfo("fceb6506-2e2c-414f-a795-852d917f319e")]
            public virtual RepoItemInfo MenuItemTracksInfo
            {
                get
                {
                    return _menuitemtracksInfo;
                }
            }

            /// <summary>
            /// The MenuItemDrop_Track item.
            /// </summary>
            [RepositoryItem("1a1ef495-35fd-45f8-9e49-b15bb41f4464")]
            public virtual Ranorex.MenuItem MenuItemDrop_Track
            {
                get
                {
                    return _menuitemdrop_trackInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemDrop_Track item info.
            /// </summary>
            [RepositoryItemInfo("1a1ef495-35fd-45f8-9e49-b15bb41f4464")]
            public virtual RepoItemInfo MenuItemDrop_TrackInfo
            {
                get
                {
                    return _menuitemdrop_trackInfo;
                }
            }
        }

        /// <summary>
        /// The FormTacViewC2AppFolder folder.
        /// </summary>
        [RepositoryFolder("a49355b1-fba5-464a-8ab0-957823894aef")]
        public partial class FormTacViewC2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _containerrvviewInfo;
            RepoItemInfo _picturetrackInfo;
            RepoItemInfo _buttonzoom_out_maxInfo;

            /// <summary>
            /// Creates a new FormTacViewC2  folder.
            /// </summary>
            public FormTacViewC2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormTacViewC2", "/form[@title~'^TacViewC2\\ \\ \\ \\(map:\\ Default']", parentFolder, 30000, true, "a49355b1-fba5-464a-8ab0-957823894aef")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "a49355b1-fba5-464a-8ab0-957823894aef");
                _containerrvviewInfo = new RepoItemInfo(this, "ContainerRvView", "element/container[@accessiblename='RvView']", 10000, null, "14e39876-2f39-45b4-a510-d9f7cfc89741");
                _picturetrackInfo = new RepoItemInfo(this, "PictureTrack", "element/container/picture[@accessiblename=$tracknum and @accessiblevalue='Track']", 60000, null, "858ad748-12ab-49c7-a061-2fc8b6f1a51d");
                _buttonzoom_out_maxInfo = new RepoItemInfo(this, "ButtonZoom_Out_Max", "element/element/toolbar[1]/button[@accessiblename='Zoom Out Max']", 10000, null, "571d1bd9-3527-4ab3-81e7-9641d2f58813");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a49355b1-fba5-464a-8ab0-957823894aef")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a49355b1-fba5-464a-8ab0-957823894aef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerRvView item.
            /// </summary>
            [RepositoryItem("14e39876-2f39-45b4-a510-d9f7cfc89741")]
            public virtual Ranorex.Container ContainerRvView
            {
                get
                {
                    return _containerrvviewInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerRvView item info.
            /// </summary>
            [RepositoryItemInfo("14e39876-2f39-45b4-a510-d9f7cfc89741")]
            public virtual RepoItemInfo ContainerRvViewInfo
            {
                get
                {
                    return _containerrvviewInfo;
                }
            }

            /// <summary>
            /// The PictureTrack item.
            /// </summary>
            [RepositoryItem("858ad748-12ab-49c7-a061-2fc8b6f1a51d")]
            public virtual Ranorex.Picture PictureTrack
            {
                get
                {
                    return _picturetrackInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The PictureTrack item info.
            /// </summary>
            [RepositoryItemInfo("858ad748-12ab-49c7-a061-2fc8b6f1a51d")]
            public virtual RepoItemInfo PictureTrackInfo
            {
                get
                {
                    return _picturetrackInfo;
                }
            }

            /// <summary>
            /// The ButtonZoom_Out_Max item.
            /// </summary>
            [RepositoryItem("571d1bd9-3527-4ab3-81e7-9641d2f58813")]
            public virtual Ranorex.Button ButtonZoom_Out_Max
            {
                get
                {
                    return _buttonzoom_out_maxInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonZoom_Out_Max item info.
            /// </summary>
            [RepositoryItemInfo("571d1bd9-3527-4ab3-81e7-9641d2f58813")]
            public virtual RepoItemInfo ButtonZoom_Out_MaxInfo
            {
                get
                {
                    return _buttonzoom_out_maxInfo;
                }
            }
        }

        /// <summary>
        /// The FormCreate_TrackAppFolder folder.
        /// </summary>
        [RepositoryFolder("b08f6db2-42d8-4894-94cf-ffa96ef59cdb")]
        public partial class FormCreate_TrackAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemc2_hostInfo;

            /// <summary>
            /// Creates a new FormCreate_Track  folder.
            /// </summary>
            public FormCreate_TrackAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormCreate_Track", "/form[@title='Create Track']", parentFolder, 30000, true, "b08f6db2-42d8-4894-94cf-ffa96ef59cdb")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "b08f6db2-42d8-4894-94cf-ffa96ef59cdb");
                _menuitemc2_hostInfo = new RepoItemInfo(this, "MenuItemC2_HOST", "contextmenu[1]/menuitem[@accessiblename='C2 HOST']", 10000, null, "1f77076d-3b76-4b97-88c1-1c98113ae88f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b08f6db2-42d8-4894-94cf-ffa96ef59cdb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b08f6db2-42d8-4894-94cf-ffa96ef59cdb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemC2_HOST item.
            /// </summary>
            [RepositoryItem("1f77076d-3b76-4b97-88c1-1c98113ae88f")]
            public virtual Ranorex.MenuItem MenuItemC2_HOST
            {
                get
                {
                    return _menuitemc2_hostInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemC2_HOST item info.
            /// </summary>
            [RepositoryItemInfo("1f77076d-3b76-4b97-88c1-1c98113ae88f")]
            public virtual RepoItemInfo MenuItemC2_HOSTInfo
            {
                get
                {
                    return _menuitemc2_hostInfo;
                }
            }
        }

        /// <summary>
        /// The FormC2_HOSTAppFolder folder.
        /// </summary>
        [RepositoryFolder("76d3d058-4a3b-439f-9042-a25044c47822")]
        public partial class FormC2_HOSTAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemsubsurfaceInfo;
            RepoItemInfo _menuitemdrop_trackInfo;
            RepoItemInfo _menuitemreference_pointInfo;

            /// <summary>
            /// Creates a new FormC2_HOST  folder.
            /// </summary>
            public FormC2_HOSTAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormC2_HOST", "/form[@title~'^C2 HOST.*']", parentFolder, 30000, true, "76d3d058-4a3b-439f-9042-a25044c47822")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "76d3d058-4a3b-439f-9042-a25044c47822");
                _menuitemsubsurfaceInfo = new RepoItemInfo(this, "MenuItemSubSurface", "contextmenu[1]/menuitem[@accessiblename='SubSurface']", 10000, null, "98f6f69e-7cd2-4399-b850-2027ce411bf3");
                _menuitemdrop_trackInfo = new RepoItemInfo(this, "MenuItemDrop_Track", "contextmenu/menuitem[@accessiblename='Drop Track']", 10000, null, "29a3db6c-d582-4f3c-9d75-8b57eb820108");
                _menuitemreference_pointInfo = new RepoItemInfo(this, "MenuItemReference_Point", "contextmenu[1]/menuitem[@accessiblename='Reference Point']", 10000, null, "27d9178f-4659-4d65-bca5-ef0c96eef989");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("76d3d058-4a3b-439f-9042-a25044c47822")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("76d3d058-4a3b-439f-9042-a25044c47822")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemSubSurface item.
            /// </summary>
            [RepositoryItem("98f6f69e-7cd2-4399-b850-2027ce411bf3")]
            public virtual Ranorex.MenuItem MenuItemSubSurface
            {
                get
                {
                    return _menuitemsubsurfaceInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemSubSurface item info.
            /// </summary>
            [RepositoryItemInfo("98f6f69e-7cd2-4399-b850-2027ce411bf3")]
            public virtual RepoItemInfo MenuItemSubSurfaceInfo
            {
                get
                {
                    return _menuitemsubsurfaceInfo;
                }
            }

            /// <summary>
            /// The MenuItemDrop_Track item.
            /// </summary>
            [RepositoryItem("29a3db6c-d582-4f3c-9d75-8b57eb820108")]
            public virtual Ranorex.MenuItem MenuItemDrop_Track
            {
                get
                {
                    return _menuitemdrop_trackInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemDrop_Track item info.
            /// </summary>
            [RepositoryItemInfo("29a3db6c-d582-4f3c-9d75-8b57eb820108")]
            public virtual RepoItemInfo MenuItemDrop_TrackInfo
            {
                get
                {
                    return _menuitemdrop_trackInfo;
                }
            }

            /// <summary>
            /// The MenuItemReference_Point item.
            /// </summary>
            [RepositoryItem("27d9178f-4659-4d65-bca5-ef0c96eef989")]
            public virtual Ranorex.MenuItem MenuItemReference_Point
            {
                get
                {
                    return _menuitemreference_pointInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemReference_Point item info.
            /// </summary>
            [RepositoryItemInfo("27d9178f-4659-4d65-bca5-ef0c96eef989")]
            public virtual RepoItemInfo MenuItemReference_PointInfo
            {
                get
                {
                    return _menuitemreference_pointInfo;
                }
            }
        }

        /// <summary>
        /// The FormMain__SubSurface_CreateAppFolder folder.
        /// </summary>
        [RepositoryFolder("fc4a2a3c-8caa-4d6f-be58-208da013154d")]
        public partial class FormMain__SubSurface_CreateAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _listitemactivityInfo;
            RepoItemInfo _listitemidentityInfo;
            RepoItemInfo _listitemplatformInfo;
            RepoItemInfo _listitemtrack_3_4_5_4_indicatorInfo;

            /// <summary>
            /// Creates a new FormMain__SubSurface_Create  folder.
            /// </summary>
            public FormMain__SubSurface_CreateAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMain__SubSurface_Create", "/form[@title~'^Main\\ \\(SubSurface\\ TN\\ \\)\\ CRE']", parentFolder, 30000, true, "fc4a2a3c-8caa-4d6f-be58-208da013154d")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "fc4a2a3c-8caa-4d6f-be58-208da013154d");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "element/container/element/toolbar[1]/button[@accessiblename='Save']", 10000, null, "e9582393-d1d1-499b-ba69-fe5f31e24c95");
                _listitemactivityInfo = new RepoItemInfo(this, "ListItemActivity", "element/container/element/element/listitem[@accessiblename='Activity']", 10000, null, "5960fd69-c223-4657-a6b9-d796b099147f");
                _listitemidentityInfo = new RepoItemInfo(this, "ListItemIdentity", "element/container/element/element/listitem[@accessiblename='Identity']", 10000, null, "c85aac79-ee9f-4592-b8f6-086e1d1c1c93");
                _listitemplatformInfo = new RepoItemInfo(this, "ListItemPlatform", "element/container/element/element/listitem[@accessiblename='Platform']", 10000, null, "58beddbe-301c-4fe1-86ee-4c9f8a22c5a8");
                _listitemtrack_3_4_5_4_indicatorInfo = new RepoItemInfo(this, "ListItemTrack_3_4_5_4_Indicator", "element/container/element/element/listitem[@accessiblename='Track 3.4/5.4 Indicator']", 10000, null, "4d4c5d51-bc13-49dd-801d-9161263fdc62");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fc4a2a3c-8caa-4d6f-be58-208da013154d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc4a2a3c-8caa-4d6f-be58-208da013154d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("e9582393-d1d1-499b-ba69-fe5f31e24c95")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("e9582393-d1d1-499b-ba69-fe5f31e24c95")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The ListItemActivity item.
            /// </summary>
            [RepositoryItem("5960fd69-c223-4657-a6b9-d796b099147f")]
            public virtual Ranorex.ListItem ListItemActivity
            {
                get
                {
                    return _listitemactivityInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemActivity item info.
            /// </summary>
            [RepositoryItemInfo("5960fd69-c223-4657-a6b9-d796b099147f")]
            public virtual RepoItemInfo ListItemActivityInfo
            {
                get
                {
                    return _listitemactivityInfo;
                }
            }

            /// <summary>
            /// The ListItemIdentity item.
            /// </summary>
            [RepositoryItem("c85aac79-ee9f-4592-b8f6-086e1d1c1c93")]
            public virtual Ranorex.ListItem ListItemIdentity
            {
                get
                {
                    return _listitemidentityInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemIdentity item info.
            /// </summary>
            [RepositoryItemInfo("c85aac79-ee9f-4592-b8f6-086e1d1c1c93")]
            public virtual RepoItemInfo ListItemIdentityInfo
            {
                get
                {
                    return _listitemidentityInfo;
                }
            }

            /// <summary>
            /// The ListItemPlatform item.
            /// </summary>
            [RepositoryItem("58beddbe-301c-4fe1-86ee-4c9f8a22c5a8")]
            public virtual Ranorex.ListItem ListItemPlatform
            {
                get
                {
                    return _listitemplatformInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPlatform item info.
            /// </summary>
            [RepositoryItemInfo("58beddbe-301c-4fe1-86ee-4c9f8a22c5a8")]
            public virtual RepoItemInfo ListItemPlatformInfo
            {
                get
                {
                    return _listitemplatformInfo;
                }
            }

            /// <summary>
            /// The ListItemTrack_3_4_5_4_Indicator item.
            /// </summary>
            [RepositoryItem("4d4c5d51-bc13-49dd-801d-9161263fdc62")]
            public virtual Ranorex.ListItem ListItemTrack_3_4_5_4_Indicator
            {
                get
                {
                    return _listitemtrack_3_4_5_4_indicatorInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTrack_3_4_5_4_Indicator item info.
            /// </summary>
            [RepositoryItemInfo("4d4c5d51-bc13-49dd-801d-9161263fdc62")]
            public virtual RepoItemInfo ListItemTrack_3_4_5_4_IndicatorInfo
            {
                get
                {
                    return _listitemtrack_3_4_5_4_indicatorInfo;
                }
            }
        }

        /// <summary>
        /// The ListRealViewAppFolder folder.
        /// </summary>
        [RepositoryFolder("1cb04e6e-e4ac-49c7-b5e8-4f13a601ae3b")]
        public partial class ListRealViewAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;

            /// <summary>
            /// Creates a new ListRealView  folder.
            /// </summary>
            public ListRealViewAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ListRealView", "/list[@processname='RealView']", parentFolder, 30000, true, "1cb04e6e-e4ac-49c7-b5e8-4f13a601ae3b")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "1cb04e6e-e4ac-49c7-b5e8-4f13a601ae3b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1cb04e6e-e4ac-49c7-b5e8-4f13a601ae3b")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1cb04e6e-e4ac-49c7-b5e8-4f13a601ae3b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The FormMain__SubSurface_PropAppFolder folder.
        /// </summary>
        [RepositoryFolder("9da2a2bc-1cb3-49ec-895f-a526f8d1ffe9")]
        public partial class FormMain__SubSurface_PropAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttoncloseInfo;
            RepoItemInfo _listitemactivityInfo;
            RepoItemInfo _listitemidentityInfo;
            RepoItemInfo _listitemplatformInfo;
            RepoItemInfo _listitemtrack_3_4_5_4_indicatorInfo;

            /// <summary>
            /// Creates a new FormMain__SubSurface_Prop  folder.
            /// </summary>
            public FormMain__SubSurface_PropAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMain__SubSurface_Prop", "/form[@title~'^Main \\(SubSurface TN.*\\)']", parentFolder, 30000, true, "9da2a2bc-1cb3-49ec-895f-a526f8d1ffe9")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "9da2a2bc-1cb3-49ec-895f-a526f8d1ffe9");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonCLOSE", "button[@accessiblename='CLOSE']", 10000, null, "07bc5e9b-4604-4eb6-8411-6db0c469b624");
                _listitemactivityInfo = new RepoItemInfo(this, "ListItemActivity", "element/container[@caption='']/element/element/listitem[@accessiblename='Activity']", 10000, null, "472c896b-71f0-4d9a-9e69-dd7174c4d78b");
                _listitemidentityInfo = new RepoItemInfo(this, "ListItemIdentity", "element/container[@caption='']/element/element/listitem[@accessiblename='Identity']", 10000, null, "9cdd0aa4-fea0-4e66-8627-05d1174bbccd");
                _listitemplatformInfo = new RepoItemInfo(this, "ListItemPlatform", "element/container[@caption='']/element/element/listitem[@accessiblename='Platform']", 10000, null, "cdf76d28-c22e-4452-995c-0c1d50f79916");
                _listitemtrack_3_4_5_4_indicatorInfo = new RepoItemInfo(this, "ListItemTrack_3_4_5_4_Indicator", "element/container[@caption='']/element/element/listitem[@accessiblename='Track 3.4/5.4 Indicator']", 10000, null, "8f5a8c86-f5c0-457f-b144-c0ed6fdfb791");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9da2a2bc-1cb3-49ec-895f-a526f8d1ffe9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9da2a2bc-1cb3-49ec-895f-a526f8d1ffe9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonCLOSE item.
            /// </summary>
            [RepositoryItem("07bc5e9b-4604-4eb6-8411-6db0c469b624")]
            public virtual Ranorex.Button ButtonCLOSE
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCLOSE item info.
            /// </summary>
            [RepositoryItemInfo("07bc5e9b-4604-4eb6-8411-6db0c469b624")]
            public virtual RepoItemInfo ButtonCLOSEInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }

            /// <summary>
            /// The ListItemActivity item.
            /// </summary>
            [RepositoryItem("472c896b-71f0-4d9a-9e69-dd7174c4d78b")]
            public virtual Ranorex.ListItem ListItemActivity
            {
                get
                {
                    return _listitemactivityInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemActivity item info.
            /// </summary>
            [RepositoryItemInfo("472c896b-71f0-4d9a-9e69-dd7174c4d78b")]
            public virtual RepoItemInfo ListItemActivityInfo
            {
                get
                {
                    return _listitemactivityInfo;
                }
            }

            /// <summary>
            /// The ListItemIdentity item.
            /// </summary>
            [RepositoryItem("9cdd0aa4-fea0-4e66-8627-05d1174bbccd")]
            public virtual Ranorex.ListItem ListItemIdentity
            {
                get
                {
                    return _listitemidentityInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemIdentity item info.
            /// </summary>
            [RepositoryItemInfo("9cdd0aa4-fea0-4e66-8627-05d1174bbccd")]
            public virtual RepoItemInfo ListItemIdentityInfo
            {
                get
                {
                    return _listitemidentityInfo;
                }
            }

            /// <summary>
            /// The ListItemPlatform item.
            /// </summary>
            [RepositoryItem("cdf76d28-c22e-4452-995c-0c1d50f79916")]
            public virtual Ranorex.ListItem ListItemPlatform
            {
                get
                {
                    return _listitemplatformInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPlatform item info.
            /// </summary>
            [RepositoryItemInfo("cdf76d28-c22e-4452-995c-0c1d50f79916")]
            public virtual RepoItemInfo ListItemPlatformInfo
            {
                get
                {
                    return _listitemplatformInfo;
                }
            }

            /// <summary>
            /// The ListItemTrack_3_4_5_4_Indicator item.
            /// </summary>
            [RepositoryItem("8f5a8c86-f5c0-457f-b144-c0ed6fdfb791")]
            public virtual Ranorex.ListItem ListItemTrack_3_4_5_4_Indicator
            {
                get
                {
                    return _listitemtrack_3_4_5_4_indicatorInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTrack_3_4_5_4_Indicator item info.
            /// </summary>
            [RepositoryItemInfo("8f5a8c86-f5c0-457f-b144-c0ed6fdfb791")]
            public virtual RepoItemInfo ListItemTrack_3_4_5_4_IndicatorInfo
            {
                get
                {
                    return _listitemtrack_3_4_5_4_indicatorInfo;
                }
            }
        }

        /// <summary>
        /// The FormTracksAppFolder folder.
        /// </summary>
        [RepositoryFolder("709eae15-d818-40e1-bf53-8fffc9fcb44b")]
        public partial class FormTracksAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemc2_host_2_trackInfo;
            RepoItemInfo _menuitemc2_host_trackInfo;

            /// <summary>
            /// Creates a new FormTracks  folder.
            /// </summary>
            public FormTracksAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormTracks", "/form[@title='Tracks']", parentFolder, 30000, true, "709eae15-d818-40e1-bf53-8fffc9fcb44b")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "709eae15-d818-40e1-bf53-8fffc9fcb44b");
                _menuitemc2_host_2_trackInfo = new RepoItemInfo(this, "MenuItemC2_HOST_2_Track", "contextmenu[1]/menuitem[@accessiblename='C2 HOST 2 Track#'+$tracknum or @accessiblename~'TOAD 2 Track#'+$tracknum]", 10000, null, "678c2af1-7029-4248-bbc5-1e0a57ae6158");
                _menuitemc2_host_trackInfo = new RepoItemInfo(this, "MenuItemC2_HOST_Track", "contextmenu[1]/menuitem[@accessiblename='C2 HOST Track#'+$tracknum or @accessiblename~'TOAD Track#'+$tracknum]", 10000, null, "a13f9715-e1b9-4fe0-9989-8d2db4bb5949");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("709eae15-d818-40e1-bf53-8fffc9fcb44b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("709eae15-d818-40e1-bf53-8fffc9fcb44b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemC2_HOST_2_Track item.
            /// </summary>
            [RepositoryItem("678c2af1-7029-4248-bbc5-1e0a57ae6158")]
            public virtual Ranorex.MenuItem MenuItemC2_HOST_2_Track
            {
                get
                {
                    return _menuitemc2_host_2_trackInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemC2_HOST_2_Track item info.
            /// </summary>
            [RepositoryItemInfo("678c2af1-7029-4248-bbc5-1e0a57ae6158")]
            public virtual RepoItemInfo MenuItemC2_HOST_2_TrackInfo
            {
                get
                {
                    return _menuitemc2_host_2_trackInfo;
                }
            }

            /// <summary>
            /// The MenuItemC2_HOST_Track item.
            /// </summary>
            [RepositoryItem("a13f9715-e1b9-4fe0-9989-8d2db4bb5949")]
            public virtual Ranorex.MenuItem MenuItemC2_HOST_Track
            {
                get
                {
                    return _menuitemc2_host_trackInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemC2_HOST_Track item info.
            /// </summary>
            [RepositoryItemInfo("a13f9715-e1b9-4fe0-9989-8d2db4bb5949")]
            public virtual RepoItemInfo MenuItemC2_HOST_TrackInfo
            {
                get
                {
                    return _menuitemc2_host_trackInfo;
                }
            }
        }

        /// <summary>
        /// The FormRealView1AppFolder folder.
        /// </summary>
        [RepositoryFolder("5b2ad949-bc93-4a8b-87e8-b28c44c77998")]
        public partial class FormRealView1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new FormRealView1  folder.
            /// </summary>
            public FormRealView1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormRealView1", "/form[@title='RealView']", parentFolder, 30000, true, "5b2ad949-bc93-4a8b-87e8-b28c44c77998")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5b2ad949-bc93-4a8b-87e8-b28c44c77998");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 10000, null, "baa5a211-2b29-4c77-a4c3-ea6e348e5569");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5b2ad949-bc93-4a8b-87e8-b28c44c77998")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5b2ad949-bc93-4a8b-87e8-b28c44c77998")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("baa5a211-2b29-4c77-a4c3-ea6e348e5569")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("baa5a211-2b29-4c77-a4c3-ea6e348e5569")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The FormC2_HOST_2AppFolder folder.
        /// </summary>
        [RepositoryFolder("f72c0a25-e193-473a-83ea-a0fd2b52ff98")]
        public partial class FormC2_HOST_2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemtrack_propertiesInfo;

            /// <summary>
            /// Creates a new FormC2_HOST_2  folder.
            /// </summary>
            public FormC2_HOST_2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormC2_HOST_2", "/form[@title~'^C2 HOST 2.*']", parentFolder, 30000, true, "f72c0a25-e193-473a-83ea-a0fd2b52ff98")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "f72c0a25-e193-473a-83ea-a0fd2b52ff98");
                _menuitemtrack_propertiesInfo = new RepoItemInfo(this, "MenuItemTrack_Properties", "contextmenu[1]/menuitem[@accessiblename='Track Properties']", 10000, null, "ae779f59-dbb9-4f87-9aec-bb4b0ed6f977");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f72c0a25-e193-473a-83ea-a0fd2b52ff98")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f72c0a25-e193-473a-83ea-a0fd2b52ff98")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemTrack_Properties item.
            /// </summary>
            [RepositoryItem("ae779f59-dbb9-4f87-9aec-bb4b0ed6f977")]
            public virtual Ranorex.MenuItem MenuItemTrack_Properties
            {
                get
                {
                    return _menuitemtrack_propertiesInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemTrack_Properties item info.
            /// </summary>
            [RepositoryItemInfo("ae779f59-dbb9-4f87-9aec-bb4b0ed6f977")]
            public virtual RepoItemInfo MenuItemTrack_PropertiesInfo
            {
                get
                {
                    return _menuitemtrack_propertiesInfo;
                }
            }
        }

        /// <summary>
        /// The RealViewDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("b95f943f-5f28-47cc-9bf7-6820c167cce3")]
        public partial class RealViewDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new RealViewDialog  folder.
            /// </summary>
            public RealViewDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RealViewDialog", "/form[@title='RealView']", parentFolder, 30000, true, "b95f943f-5f28-47cc-9bf7-6820c167cce3")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "b95f943f-5f28-47cc-9bf7-6820c167cce3");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 10000, null, "8dd1b863-fe65-4f89-853f-d7153d936dfc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b95f943f-5f28-47cc-9bf7-6820c167cce3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b95f943f-5f28-47cc-9bf7-6820c167cce3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("8dd1b863-fe65-4f89-853f-d7153d936dfc")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("8dd1b863-fe65-4f89-853f-d7153d936dfc")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The FormMain__Reference_Point_TNAppFolder folder.
        /// </summary>
        [RepositoryFolder("1ff358b2-8ad3-4bbd-b9db-7aec15063e61")]
        public partial class FormMain__Reference_Point_TNAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _listitemtime_function_1Info;
            RepoItemInfo _listitemhour1Info;
            RepoItemInfo _listitemminute1Info;
            RepoItemInfo _listitemtime_function_2Info;
            RepoItemInfo _listitemhour2Info;
            RepoItemInfo _listitemminute2Info;
            RepoItemInfo _buttoncloseInfo;
            RepoItemInfo _listitemamplificationInfo;
            RepoItemInfo _listitempoint_typeInfo;
            RepoItemInfo _listitemsonobuoy_typeInfo;
            RepoItemInfo _listitemsonobuoy_pattern_typeInfo;
            RepoItemInfo _listitemposition_and_speedInfo;
            RepoItemInfo _listiteminterface_infoInfo;
            RepoItemInfo _listitemspecial_codesInfo;
            RepoItemInfo _listitemindicatorsInfo;
            RepoItemInfo _listitemreference_point_infoInfo;
            RepoItemInfo _listitemrelated_track_infoInfo;

            /// <summary>
            /// Creates a new FormMain__Reference_Point_TN  folder.
            /// </summary>
            public FormMain__Reference_Point_TNAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMain__Reference_Point_TN", "/form[@title~'Main \\(Reference Point TN \\) CRE']", parentFolder, 30000, false, "1ff358b2-8ad3-4bbd-b9db-7aec15063e61")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "1ff358b2-8ad3-4bbd-b9db-7aec15063e61");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", ".//button[@accessiblename='Save']", 10000, null, "74f35209-2d31-4cd9-8eaf-2d1177302df2");
                _listitemtime_function_1Info = new RepoItemInfo(this, "ListItemTime_Function_1", "element//listitem[@accessiblename='Time Function']", 10000, null, "706e7e38-6e9b-4cee-8650-111452168dad");
                _listitemhour1Info = new RepoItemInfo(this, "ListItemHour1", "element//listitem[@accessiblename='Hour']", 10000, null, "d874da3c-3dea-49fb-b04f-791a2d19ca70");
                _listitemminute1Info = new RepoItemInfo(this, "ListItemMinute1", "element//listitem[@accessiblename='Minute']", 10000, null, "d7b86b48-e921-44fd-9e97-ce881f37a189");
                _listitemtime_function_2Info = new RepoItemInfo(this, "ListItemTime_Function_2", "element//listitem[@accessiblename='Time Function 2']", 10000, null, "3a9ed53e-64be-4e9e-a56e-dd43808ce1d0");
                _listitemhour2Info = new RepoItemInfo(this, "ListItemHour2", "element//listitem[@accessiblename='Hour 2']", 10000, null, "b5852be6-b27c-4a7d-a2ea-38fe67f132a3");
                _listitemminute2Info = new RepoItemInfo(this, "ListItemMinute2", "element//listitem[@accessiblename='Minute 2']", 10000, null, "91a6dd22-af79-4846-9310-90c08c2b9d87");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonCLOSE", "button[@accessiblename='CLOSE']", 10000, null, "2595fcc5-212b-4b22-961b-7c885a3d4a04");
                _listitemamplificationInfo = new RepoItemInfo(this, "ListItemAmplification", "element//listitem[@accessiblename='Amplification']", 10000, null, "88a3dcbc-690c-42f1-839f-a72e7dc48535");
                _listitempoint_typeInfo = new RepoItemInfo(this, "ListItemPoint_Type", "element//listitem[@accessiblename='Point Type']", 10000, null, "be38d5f5-f7b6-4dbc-b2e1-33dead0efab1");
                _listitemsonobuoy_typeInfo = new RepoItemInfo(this, "ListItemSonobuoy_Type", "element//listitem[@accessiblename='Sonobuoy Type']", 10000, null, "484c9a5b-495a-4452-885b-f44b517fa920");
                _listitemsonobuoy_pattern_typeInfo = new RepoItemInfo(this, "ListItemSonobuoy_Pattern_Type", "element//listitem[@accessiblename='Sonobuoy Pattern Type']", 10000, null, "303f3ab5-2788-4262-bbc9-66f0f4406ff1");
                _listitemposition_and_speedInfo = new RepoItemInfo(this, "ListItemPosition_and_Speed", "element/container/element/element/listitem[@accessiblename='Position and Speed']", 10000, null, "581fddbf-bb1a-4390-b642-046cef6c9c37");
                _listiteminterface_infoInfo = new RepoItemInfo(this, "ListItemInterface_Info", "element/container/element/element/listitem[@accessiblename='Interface Info']", 10000, null, "8a18b31a-2bb2-4e7f-8ccb-b67b2fa495b4");
                _listitemspecial_codesInfo = new RepoItemInfo(this, "ListItemSpecial_Codes", "element/container/element/element/listitem[@accessiblename='Special Codes']", 10000, null, "58d375d0-a2cf-452a-a677-59dad4f7a32d");
                _listitemindicatorsInfo = new RepoItemInfo(this, "ListItemIndicators", "element/container/element/element/listitem[@accessiblename='Indicators']", 10000, null, "ef342423-4a7e-4e2a-8b62-2ebda082b701");
                _listitemreference_point_infoInfo = new RepoItemInfo(this, "ListItemReference_Point_Info", "element/container/element/element/listitem[@accessiblename='Reference Point Info']", 10000, null, "2596e31f-0fdb-4dca-9930-2137f3000f08");
                _listitemrelated_track_infoInfo = new RepoItemInfo(this, "ListItemRelated_Track_Info", "element/container/element/element/listitem[@accessiblename='Related Track Info']", 10000, null, "2a1bc037-796b-4c77-96a2-eb41778ad915");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1ff358b2-8ad3-4bbd-b9db-7aec15063e61")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1ff358b2-8ad3-4bbd-b9db-7aec15063e61")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("74f35209-2d31-4cd9-8eaf-2d1177302df2")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("74f35209-2d31-4cd9-8eaf-2d1177302df2")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The ListItemTime_Function_1 item.
            /// </summary>
            [RepositoryItem("706e7e38-6e9b-4cee-8650-111452168dad")]
            public virtual Ranorex.ListItem ListItemTime_Function_1
            {
                get
                {
                    return _listitemtime_function_1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTime_Function_1 item info.
            /// </summary>
            [RepositoryItemInfo("706e7e38-6e9b-4cee-8650-111452168dad")]
            public virtual RepoItemInfo ListItemTime_Function_1Info
            {
                get
                {
                    return _listitemtime_function_1Info;
                }
            }

            /// <summary>
            /// The ListItemHour1 item.
            /// </summary>
            [RepositoryItem("d874da3c-3dea-49fb-b04f-791a2d19ca70")]
            public virtual Ranorex.ListItem ListItemHour1
            {
                get
                {
                    return _listitemhour1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemHour1 item info.
            /// </summary>
            [RepositoryItemInfo("d874da3c-3dea-49fb-b04f-791a2d19ca70")]
            public virtual RepoItemInfo ListItemHour1Info
            {
                get
                {
                    return _listitemhour1Info;
                }
            }

            /// <summary>
            /// The ListItemMinute1 item.
            /// </summary>
            [RepositoryItem("d7b86b48-e921-44fd-9e97-ce881f37a189")]
            public virtual Ranorex.ListItem ListItemMinute1
            {
                get
                {
                    return _listitemminute1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemMinute1 item info.
            /// </summary>
            [RepositoryItemInfo("d7b86b48-e921-44fd-9e97-ce881f37a189")]
            public virtual RepoItemInfo ListItemMinute1Info
            {
                get
                {
                    return _listitemminute1Info;
                }
            }

            /// <summary>
            /// The ListItemTime_Function_2 item.
            /// </summary>
            [RepositoryItem("3a9ed53e-64be-4e9e-a56e-dd43808ce1d0")]
            public virtual Ranorex.ListItem ListItemTime_Function_2
            {
                get
                {
                    return _listitemtime_function_2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemTime_Function_2 item info.
            /// </summary>
            [RepositoryItemInfo("3a9ed53e-64be-4e9e-a56e-dd43808ce1d0")]
            public virtual RepoItemInfo ListItemTime_Function_2Info
            {
                get
                {
                    return _listitemtime_function_2Info;
                }
            }

            /// <summary>
            /// The ListItemHour2 item.
            /// </summary>
            [RepositoryItem("b5852be6-b27c-4a7d-a2ea-38fe67f132a3")]
            public virtual Ranorex.ListItem ListItemHour2
            {
                get
                {
                    return _listitemhour2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemHour2 item info.
            /// </summary>
            [RepositoryItemInfo("b5852be6-b27c-4a7d-a2ea-38fe67f132a3")]
            public virtual RepoItemInfo ListItemHour2Info
            {
                get
                {
                    return _listitemhour2Info;
                }
            }

            /// <summary>
            /// The ListItemMinute2 item.
            /// </summary>
            [RepositoryItem("91a6dd22-af79-4846-9310-90c08c2b9d87")]
            public virtual Ranorex.ListItem ListItemMinute2
            {
                get
                {
                    return _listitemminute2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemMinute2 item info.
            /// </summary>
            [RepositoryItemInfo("91a6dd22-af79-4846-9310-90c08c2b9d87")]
            public virtual RepoItemInfo ListItemMinute2Info
            {
                get
                {
                    return _listitemminute2Info;
                }
            }

            /// <summary>
            /// The ButtonCLOSE item.
            /// </summary>
            [RepositoryItem("2595fcc5-212b-4b22-961b-7c885a3d4a04")]
            public virtual Ranorex.Button ButtonCLOSE
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCLOSE item info.
            /// </summary>
            [RepositoryItemInfo("2595fcc5-212b-4b22-961b-7c885a3d4a04")]
            public virtual RepoItemInfo ButtonCLOSEInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }

            /// <summary>
            /// The ListItemAmplification item.
            /// </summary>
            [RepositoryItem("88a3dcbc-690c-42f1-839f-a72e7dc48535")]
            public virtual Ranorex.ListItem ListItemAmplification
            {
                get
                {
                    return _listitemamplificationInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemAmplification item info.
            /// </summary>
            [RepositoryItemInfo("88a3dcbc-690c-42f1-839f-a72e7dc48535")]
            public virtual RepoItemInfo ListItemAmplificationInfo
            {
                get
                {
                    return _listitemamplificationInfo;
                }
            }

            /// <summary>
            /// The ListItemPoint_Type item.
            /// </summary>
            [RepositoryItem("be38d5f5-f7b6-4dbc-b2e1-33dead0efab1")]
            public virtual Ranorex.ListItem ListItemPoint_Type
            {
                get
                {
                    return _listitempoint_typeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPoint_Type item info.
            /// </summary>
            [RepositoryItemInfo("be38d5f5-f7b6-4dbc-b2e1-33dead0efab1")]
            public virtual RepoItemInfo ListItemPoint_TypeInfo
            {
                get
                {
                    return _listitempoint_typeInfo;
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Type item.
            /// </summary>
            [RepositoryItem("484c9a5b-495a-4452-885b-f44b517fa920")]
            public virtual Ranorex.ListItem ListItemSonobuoy_Type
            {
                get
                {
                    return _listitemsonobuoy_typeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Type item info.
            /// </summary>
            [RepositoryItemInfo("484c9a5b-495a-4452-885b-f44b517fa920")]
            public virtual RepoItemInfo ListItemSonobuoy_TypeInfo
            {
                get
                {
                    return _listitemsonobuoy_typeInfo;
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Pattern_Type item.
            /// </summary>
            [RepositoryItem("303f3ab5-2788-4262-bbc9-66f0f4406ff1")]
            public virtual Ranorex.ListItem ListItemSonobuoy_Pattern_Type
            {
                get
                {
                    return _listitemsonobuoy_pattern_typeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Pattern_Type item info.
            /// </summary>
            [RepositoryItemInfo("303f3ab5-2788-4262-bbc9-66f0f4406ff1")]
            public virtual RepoItemInfo ListItemSonobuoy_Pattern_TypeInfo
            {
                get
                {
                    return _listitemsonobuoy_pattern_typeInfo;
                }
            }

            /// <summary>
            /// The ListItemPosition_and_Speed item.
            /// </summary>
            [RepositoryItem("581fddbf-bb1a-4390-b642-046cef6c9c37")]
            public virtual Ranorex.ListItem ListItemPosition_and_Speed
            {
                get
                {
                    return _listitemposition_and_speedInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPosition_and_Speed item info.
            /// </summary>
            [RepositoryItemInfo("581fddbf-bb1a-4390-b642-046cef6c9c37")]
            public virtual RepoItemInfo ListItemPosition_and_SpeedInfo
            {
                get
                {
                    return _listitemposition_and_speedInfo;
                }
            }

            /// <summary>
            /// The ListItemInterface_Info item.
            /// </summary>
            [RepositoryItem("8a18b31a-2bb2-4e7f-8ccb-b67b2fa495b4")]
            public virtual Ranorex.ListItem ListItemInterface_Info
            {
                get
                {
                    return _listiteminterface_infoInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemInterface_Info item info.
            /// </summary>
            [RepositoryItemInfo("8a18b31a-2bb2-4e7f-8ccb-b67b2fa495b4")]
            public virtual RepoItemInfo ListItemInterface_InfoInfo
            {
                get
                {
                    return _listiteminterface_infoInfo;
                }
            }

            /// <summary>
            /// The ListItemSpecial_Codes item.
            /// </summary>
            [RepositoryItem("58d375d0-a2cf-452a-a677-59dad4f7a32d")]
            public virtual Ranorex.ListItem ListItemSpecial_Codes
            {
                get
                {
                    return _listitemspecial_codesInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSpecial_Codes item info.
            /// </summary>
            [RepositoryItemInfo("58d375d0-a2cf-452a-a677-59dad4f7a32d")]
            public virtual RepoItemInfo ListItemSpecial_CodesInfo
            {
                get
                {
                    return _listitemspecial_codesInfo;
                }
            }

            /// <summary>
            /// The ListItemIndicators item.
            /// </summary>
            [RepositoryItem("ef342423-4a7e-4e2a-8b62-2ebda082b701")]
            public virtual Ranorex.ListItem ListItemIndicators
            {
                get
                {
                    return _listitemindicatorsInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemIndicators item info.
            /// </summary>
            [RepositoryItemInfo("ef342423-4a7e-4e2a-8b62-2ebda082b701")]
            public virtual RepoItemInfo ListItemIndicatorsInfo
            {
                get
                {
                    return _listitemindicatorsInfo;
                }
            }

            /// <summary>
            /// The ListItemReference_Point_Info item.
            /// </summary>
            [RepositoryItem("2596e31f-0fdb-4dca-9930-2137f3000f08")]
            public virtual Ranorex.ListItem ListItemReference_Point_Info
            {
                get
                {
                    return _listitemreference_point_infoInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemReference_Point_Info item info.
            /// </summary>
            [RepositoryItemInfo("2596e31f-0fdb-4dca-9930-2137f3000f08")]
            public virtual RepoItemInfo ListItemReference_Point_InfoInfo
            {
                get
                {
                    return _listitemreference_point_infoInfo;
                }
            }

            /// <summary>
            /// The ListItemRelated_Track_Info item.
            /// </summary>
            [RepositoryItem("2a1bc037-796b-4c77-96a2-eb41778ad915")]
            public virtual Ranorex.ListItem ListItemRelated_Track_Info
            {
                get
                {
                    return _listitemrelated_track_infoInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemRelated_Track_Info item info.
            /// </summary>
            [RepositoryItemInfo("2a1bc037-796b-4c77-96a2-eb41778ad915")]
            public virtual RepoItemInfo ListItemRelated_Track_InfoInfo
            {
                get
                {
                    return _listitemrelated_track_infoInfo;
                }
            }
        }

        /// <summary>
        /// The FormTOAD2AppFolder folder.
        /// </summary>
        [RepositoryFolder("f854273f-73ce-456e-8a86-dd38490a2a31")]
        public partial class FormTOAD2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _menuitemtrack_propertiesInfo;

            /// <summary>
            /// Creates a new FormTOAD2  folder.
            /// </summary>
            public FormTOAD2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormTOAD2", "/form[@title~'C2 HOST 2.*|TOAD2.*']", parentFolder, 30000, true, "f854273f-73ce-456e-8a86-dd38490a2a31")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "f854273f-73ce-456e-8a86-dd38490a2a31");
                _menuitemtrack_propertiesInfo = new RepoItemInfo(this, "MenuItemTrack_Properties", "contextmenu[1]/menuitem[@accessiblename='Track Properties']", 10000, null, "1b07d817-8b08-42c8-b75a-82b9f8ef48b9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f854273f-73ce-456e-8a86-dd38490a2a31")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f854273f-73ce-456e-8a86-dd38490a2a31")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemTrack_Properties item.
            /// </summary>
            [RepositoryItem("1b07d817-8b08-42c8-b75a-82b9f8ef48b9")]
            public virtual Ranorex.MenuItem MenuItemTrack_Properties
            {
                get
                {
                    return _menuitemtrack_propertiesInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemTrack_Properties item info.
            /// </summary>
            [RepositoryItemInfo("1b07d817-8b08-42c8-b75a-82b9f8ef48b9")]
            public virtual RepoItemInfo MenuItemTrack_PropertiesInfo
            {
                get
                {
                    return _menuitemtrack_propertiesInfo;
                }
            }
        }

        /// <summary>
        /// The FormMain__Reference_Point_TNPropAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f48873c-eabe-4f58-a403-54cd0ec65b38")]
        public partial class FormMain__Reference_Point_TNPropAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttoncloseInfo;
            RepoItemInfo _listitempoint_typeInfo;
            RepoItemInfo _listitemamplificationInfo;
            RepoItemInfo _listitemsonobuoy_typeInfo;
            RepoItemInfo _listitemsonobuoy_pattern_typeInfo;

            /// <summary>
            /// Creates a new FormMain__Reference_Point_TNProp  folder.
            /// </summary>
            public FormMain__Reference_Point_TNPropAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMain__Reference_Point_TNProp", "/form[@title~'^Main \\(Reference Point TN.* ']", parentFolder, 30000, true, "9f48873c-eabe-4f58-a403-54cd0ec65b38")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "9f48873c-eabe-4f58-a403-54cd0ec65b38");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonCLOSE", "button[@accessiblename='CLOSE']", 10000, null, "c207e498-0e41-439d-9750-0294997a471d");
                _listitempoint_typeInfo = new RepoItemInfo(this, "ListItemPoint_Type", "element/container[@caption='']/element/element/listitem[@accessiblename='Point Type']", 10000, null, "66fa7581-9386-4ca3-8833-9261e02d0b70");
                _listitemamplificationInfo = new RepoItemInfo(this, "ListItemAmplification", "element/container[@caption='']/element/element/listitem[@accessiblename='Amplification']", 10000, null, "5e10ec65-e2e5-4fe8-becf-cb4da42806c0");
                _listitemsonobuoy_typeInfo = new RepoItemInfo(this, "ListItemSonobuoy_Type", "element/container[@caption='']/element/element/listitem[@accessiblename='Sonobuoy Type']", 10000, null, "d55d644b-5c71-4c75-86ab-4189c536d308");
                _listitemsonobuoy_pattern_typeInfo = new RepoItemInfo(this, "ListItemSonobuoy_Pattern_Type", "element/container[@caption='']/element/element/listitem[@accessiblename='Sonobuoy Pattern Type']", 10000, null, "989e423f-52d9-4a13-9c44-9f866c74236b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f48873c-eabe-4f58-a403-54cd0ec65b38")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f48873c-eabe-4f58-a403-54cd0ec65b38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonCLOSE item.
            /// </summary>
            [RepositoryItem("c207e498-0e41-439d-9750-0294997a471d")]
            public virtual Ranorex.Button ButtonCLOSE
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCLOSE item info.
            /// </summary>
            [RepositoryItemInfo("c207e498-0e41-439d-9750-0294997a471d")]
            public virtual RepoItemInfo ButtonCLOSEInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }

            /// <summary>
            /// The ListItemPoint_Type item.
            /// </summary>
            [RepositoryItem("66fa7581-9386-4ca3-8833-9261e02d0b70")]
            public virtual Ranorex.ListItem ListItemPoint_Type
            {
                get
                {
                    return _listitempoint_typeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemPoint_Type item info.
            /// </summary>
            [RepositoryItemInfo("66fa7581-9386-4ca3-8833-9261e02d0b70")]
            public virtual RepoItemInfo ListItemPoint_TypeInfo
            {
                get
                {
                    return _listitempoint_typeInfo;
                }
            }

            /// <summary>
            /// The ListItemAmplification item.
            /// </summary>
            [RepositoryItem("5e10ec65-e2e5-4fe8-becf-cb4da42806c0")]
            public virtual Ranorex.ListItem ListItemAmplification
            {
                get
                {
                    return _listitemamplificationInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemAmplification item info.
            /// </summary>
            [RepositoryItemInfo("5e10ec65-e2e5-4fe8-becf-cb4da42806c0")]
            public virtual RepoItemInfo ListItemAmplificationInfo
            {
                get
                {
                    return _listitemamplificationInfo;
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Type item.
            /// </summary>
            [RepositoryItem("d55d644b-5c71-4c75-86ab-4189c536d308")]
            public virtual Ranorex.ListItem ListItemSonobuoy_Type
            {
                get
                {
                    return _listitemsonobuoy_typeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Type item info.
            /// </summary>
            [RepositoryItemInfo("d55d644b-5c71-4c75-86ab-4189c536d308")]
            public virtual RepoItemInfo ListItemSonobuoy_TypeInfo
            {
                get
                {
                    return _listitemsonobuoy_typeInfo;
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Pattern_Type item.
            /// </summary>
            [RepositoryItem("989e423f-52d9-4a13-9c44-9f866c74236b")]
            public virtual Ranorex.ListItem ListItemSonobuoy_Pattern_Type
            {
                get
                {
                    return _listitemsonobuoy_pattern_typeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemSonobuoy_Pattern_Type item info.
            /// </summary>
            [RepositoryItemInfo("989e423f-52d9-4a13-9c44-9f866c74236b")]
            public virtual RepoItemInfo ListItemSonobuoy_Pattern_TypeInfo
            {
                get
                {
                    return _listitemsonobuoy_pattern_typeInfo;
                }
            }
        }

        /// <summary>
        /// The FormMainAppFolder folder.
        /// </summary>
        [RepositoryFolder("160fa4ee-ce39-499c-8b4d-396f3d7c58ae")]
        public partial class FormMainAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _buttonsaveInfo;
            RepoItemInfo _listitemstrengthInfo;
            RepoItemInfo _buttoncloseInfo;

            /// <summary>
            /// Creates a new FormMain  folder.
            /// </summary>
            public FormMainAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormMain", "/form[@title~'^Main\\ ']", parentFolder, 30000, true, "160fa4ee-ce39-499c-8b4d-396f3d7c58ae")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "160fa4ee-ce39-499c-8b4d-396f3d7c58ae");
                _buttonsaveInfo = new RepoItemInfo(this, "ButtonSave", "element/container/element/toolbar[1]/button[@accessiblename='Save']", 10000, null, "76715f4e-8fac-4af5-a80b-82734a99c5bd");
                _listitemstrengthInfo = new RepoItemInfo(this, "ListItemStrength", "element/container/element/element/listitem[@accessiblename='Strength']", 10000, null, "be9fbfca-ec22-4996-b0c5-33fceadfb202");
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonCLOSE", "button[@accessiblename='CLOSE']", 10000, null, "b225e71c-82e6-4984-88dc-711d23bcd1de");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("160fa4ee-ce39-499c-8b4d-396f3d7c58ae")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("160fa4ee-ce39-499c-8b4d-396f3d7c58ae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonSave item.
            /// </summary>
            [RepositoryItem("76715f4e-8fac-4af5-a80b-82734a99c5bd")]
            public virtual Ranorex.Button ButtonSave
            {
                get
                {
                    return _buttonsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSave item info.
            /// </summary>
            [RepositoryItemInfo("76715f4e-8fac-4af5-a80b-82734a99c5bd")]
            public virtual RepoItemInfo ButtonSaveInfo
            {
                get
                {
                    return _buttonsaveInfo;
                }
            }

            /// <summary>
            /// The ListItemStrength item.
            /// </summary>
            [RepositoryItem("be9fbfca-ec22-4996-b0c5-33fceadfb202")]
            public virtual Ranorex.ListItem ListItemStrength
            {
                get
                {
                    return _listitemstrengthInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ListItemStrength item info.
            /// </summary>
            [RepositoryItemInfo("be9fbfca-ec22-4996-b0c5-33fceadfb202")]
            public virtual RepoItemInfo ListItemStrengthInfo
            {
                get
                {
                    return _listitemstrengthInfo;
                }
            }

            /// <summary>
            /// The ButtonCLOSE item.
            /// </summary>
            [RepositoryItem("b225e71c-82e6-4984-88dc-711d23bcd1de")]
            public virtual Ranorex.Button ButtonCLOSE
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCLOSE item info.
            /// </summary>
            [RepositoryItemInfo("b225e71c-82e6-4984-88dc-711d23bcd1de")]
            public virtual RepoItemInfo ButtonCLOSEInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }
        }

    }
}
