///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.UISpecific.Configuration
{
	/// <summary>
	/// The ConfigureTOADIP recording.
	/// </summary>
	public partial class ConfigureTOADIP
	{
		public static TacViewLib.TacViewLibRepository repo = TacViewLib.TacViewLibRepository.Instance;

		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "2.2.2")]
		public static void Start()
		{
			Mouse.DefaultMoveTime = 300;
			Keyboard.DefaultKeyPressTime = 100;
			Delay.SpeedFactor = 1.0;

			Report.Info("Mouse Right Click item 'FormTacViewC2____map__Pacifi1.CellInterface_0_1' at 35;11.");
			repo.FormTacViewC2____map__Pacifi1.CellInterface_0_1.Click(MouseButtons.Right, "35;11");
			Delay.Milliseconds(0);
			Report.Info("Mouse Left Click item 'FormRealView11.MenuItemInterface_Properties1' at 32;7.");
			repo.FormRealView11.MenuItemInterface_Properties1.Click("32;7");
			Delay.Milliseconds(0);
			Report.Info("Mouse Left Click item 'FormInterface_Properties.FormInterface_Properties' at 207;19.");
			repo.FormInterface_Properties.FormInterface_Properties.Click("207;19");
			Delay.Milliseconds(0);
			Report.Info("Mouse Left Click item 'FormInterface_Properties.ButtonENTRANSPARENCY' at 5;11.");
			repo.FormInterface_Properties.ButtonENTRANSPARENCY.Click("5;11");
			Delay.Milliseconds(0);
			Report.Info("Mouse Left Click item 'FormInterface_Properties.TabPageConnection_Settings1' at 76;6.");
			repo.FormInterface_Properties.TabPageConnection_Settings1.Click("76;6");
			Delay.Milliseconds(0);
			Report.Info("Mouse Left Click item 'FormConnection_Settings.ToolBarToolBar.ButtonEdit' at 24;23.");
			repo.FormConnection_Settings.ToolBarToolBar.ButtonEdit.Click("24;23");
			Delay.Milliseconds(0);
			Report.Info("Mouse Left Click item 'FormConnection_Settings.ContainerRealView1.ListItemServer_Address1' at 70;6.");
			repo.FormConnection_Settings.ContainerRealView1.ListItemServer_Address1.Click("70;6");
			Delay.Milliseconds(0);
			Report.Info("Key sequence '172.16.99.176'.");
			Keyboard.Press("172.16.99.176");
			Delay.Milliseconds(0);
			Report.Info("Key sequence '{Return}{Return}{Return}'.");
			Keyboard.Press("{Return}{Return}{Return}");
			Delay.Milliseconds(0);
			Report.Info("Key 'Return' Press.");
			Keyboard.Press(Keys.Return, 28, Keyboard.DefaultKeyPressTime, 1, false);
			Delay.Milliseconds(150);
			Report.Info("Mouse Left Click item 'FormConnection_Settings.ButtonCLOSE1' at 7;10.");
			repo.FormConnection_Settings.ButtonCLOSE1.Click("7;10");
			Delay.Milliseconds(0);
			Delay.Milliseconds(500, false);
		}

#region Image Feature Data
#endregion
	}
}

