///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace TacViewLib.UISpecific.Configuration
{
	/// <summary>
	/// The EnterInterface1IP recording.
	/// </summary>
	[TestModule("ad546df6-9e33-48f3-b494-7b0e4971416a", ModuleType.Recording, 1)]
	public partial class EnterInterface1IP : ITestModule
	{
		/// <summary>
		/// Holds an instance of the TacViewLib.TacViewLibRepositoryConfiguration repository.
		/// </summary>
		public static TacViewLib.TacViewLibRepositoryConfiguration repo = TacViewLib.TacViewLibRepositoryConfiguration.Instance;

		static EnterInterface1IP instance = new EnterInterface1IP();

		/// <summary>
		/// Constructs a new instance.
		/// </summary>
		public EnterInterface1IP()
		{
		}

		/// <summary>
		/// Gets a static instance of this recording.
		/// </summary>
		public static EnterInterface1IP Instance
		{
			get { return instance; }
		}

#region Variables

#endregion

		/// <summary>
		/// Starts the replay of the static recording <see cref="Instance"/>.
		/// </summary>
		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.0")]
		public static void Start()
		{
			TestModuleRunner.Run(Instance);
		}

		/// <summary>
		/// Performs the playback of actions in this recording.
		/// </summary>
		/// <remarks>You should not call this method directly, instead pass the module
		/// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
		/// that will in turn invoke this method.</remarks>
		[System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.0.0")]
		void ITestModule.Run()
		{
			Mouse.DefaultMoveTime = 150;
			Keyboard.DefaultKeyPressTime = 25;
			Delay.SpeedFactor = 1.0;

			Init();

			Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'FormTacViewC2.INTERFACE_ONE' at Center.", repo.FormTacViewC2.INTERFACE_ONEInfo, new RecordItemIndex(0));
			repo.FormTacViewC2.INTERFACE_ONE.Click(MouseButtons.Right, 125);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TOAD_Context_Menu.Interface_Properties_Context_Menu' at Center.", repo.TOAD_Context_Menu.Interface_Properties_Context_MenuInfo, new RecordItemIndex(1));
			repo.TOAD_Context_Menu.Interface_Properties_Context_Menu.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TOAD_Interface_Properties.Connection_Settings_Tab' at Center.", repo.TOAD_Interface_Properties.Connection_Settings_TabInfo, new RecordItemIndex(2));
			repo.TOAD_Interface_Properties.Connection_Settings_Tab.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TOAD_Connection_Settings.Edit' at Center.", repo.TOAD_Connection_Settings.EditInfo, new RecordItemIndex(3));
			repo.TOAD_Connection_Settings.Edit.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TOAD_Connection_Settings.Server_Address' at CenterLeft.", repo.TOAD_Connection_Settings.Server_AddressInfo, new RecordItemIndex(4));
			repo.TOAD_Connection_Settings.Server_Address.Click(Location.CenterLeft);
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(5));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			IPAdress1();
			Delay.Milliseconds(150);
			
			Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(7));
			Keyboard.Press(Keys.Tab, Keyboard.DefaultScanCode, 100, 1, true);
			Delay.Milliseconds(50);
			
			ServerPort1();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TOAD_Connection_Settings.ButtonSave' at Center.", repo.TOAD_Connection_Settings.ButtonSaveInfo, new RecordItemIndex(9));
			repo.TOAD_Connection_Settings.ButtonSave.Click();
			Delay.Milliseconds(0);
			
			Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TOAD_Interface_Properties.Close' at Center.", repo.TOAD_Interface_Properties.CloseInfo, new RecordItemIndex(10));
			repo.TOAD_Interface_Properties.Close.Click();
			Delay.Milliseconds(0);
			
			EnableInterface1();
			Delay.Milliseconds(150);
			
		}

#region Image Feature Data
#endregion
	}
}
