///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using System.Windows.Forms;

using Ranorex;
using Ranorex.Core;

namespace TacViewLib.UISpecific.Configuration
{
	/// <summary>
	/// The LaunchTacViewAll recording.
	/// </summary>
	public partial class LaunchTacViewAll
	{
		static LaunchTacViewAll()
		{
			//Your recording specific initialization code goes here.
		}
		
		public void LaunchTacViewAllApp() 
        {
        	try
			{
				TacViewLib.UISpecific.Configuration.Common.LaunchShortcut("TacViewAll");
			}
			catch(Exception)
			{
				Report.Error("There is no TacViewAll desktop icon to run.");
				Environment.Exit(-1);                	
			}
		}

		private void Init()
		{
			// Your recording specific initialization code goes here.
		}

	}
}
